//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocateInitParameters) DeepCopyInto(out *AllocateInitParameters) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(string)
		**out = **in
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(string)
		**out = **in
	}
	if in.NumberOfReplicas != nil {
		in, out := &in.NumberOfReplicas, &out.NumberOfReplicas
		*out = new(float64)
		**out = **in
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = new(string)
		**out = **in
	}
	if in.TotalShardsPerNode != nil {
		in, out := &in.TotalShardsPerNode, &out.TotalShardsPerNode
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocateInitParameters.
func (in *AllocateInitParameters) DeepCopy() *AllocateInitParameters {
	if in == nil {
		return nil
	}
	out := new(AllocateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocateObservation) DeepCopyInto(out *AllocateObservation) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(string)
		**out = **in
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(string)
		**out = **in
	}
	if in.NumberOfReplicas != nil {
		in, out := &in.NumberOfReplicas, &out.NumberOfReplicas
		*out = new(float64)
		**out = **in
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = new(string)
		**out = **in
	}
	if in.TotalShardsPerNode != nil {
		in, out := &in.TotalShardsPerNode, &out.TotalShardsPerNode
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocateObservation.
func (in *AllocateObservation) DeepCopy() *AllocateObservation {
	if in == nil {
		return nil
	}
	out := new(AllocateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AllocateParameters) DeepCopyInto(out *AllocateParameters) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(string)
		**out = **in
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(string)
		**out = **in
	}
	if in.NumberOfReplicas != nil {
		in, out := &in.NumberOfReplicas, &out.NumberOfReplicas
		*out = new(float64)
		**out = **in
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = new(string)
		**out = **in
	}
	if in.TotalShardsPerNode != nil {
		in, out := &in.TotalShardsPerNode, &out.TotalShardsPerNode
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AllocateParameters.
func (in *AllocateParameters) DeepCopy() *AllocateParameters {
	if in == nil {
		return nil
	}
	out := new(AllocateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColdInitParameters) DeepCopyInto(out *ColdInitParameters) {
	*out = *in
	if in.Allocate != nil {
		in, out := &in.Allocate, &out.Allocate
		*out = make([]AllocateInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Downsample != nil {
		in, out := &in.Downsample, &out.Downsample
		*out = make([]DownsampleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Freeze != nil {
		in, out := &in.Freeze, &out.Freeze
		*out = make([]FreezeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = make([]MigrateInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = make([]ReadonlyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SearchableSnapshot != nil {
		in, out := &in.SearchableSnapshot, &out.SearchableSnapshot
		*out = make([]SearchableSnapshotInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetPriority != nil {
		in, out := &in.SetPriority, &out.SetPriority
		*out = make([]SetPriorityInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unfollow != nil {
		in, out := &in.Unfollow, &out.Unfollow
		*out = make([]UnfollowInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColdInitParameters.
func (in *ColdInitParameters) DeepCopy() *ColdInitParameters {
	if in == nil {
		return nil
	}
	out := new(ColdInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColdObservation) DeepCopyInto(out *ColdObservation) {
	*out = *in
	if in.Allocate != nil {
		in, out := &in.Allocate, &out.Allocate
		*out = make([]AllocateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Downsample != nil {
		in, out := &in.Downsample, &out.Downsample
		*out = make([]DownsampleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Freeze != nil {
		in, out := &in.Freeze, &out.Freeze
		*out = make([]FreezeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = make([]MigrateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = make([]ReadonlyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SearchableSnapshot != nil {
		in, out := &in.SearchableSnapshot, &out.SearchableSnapshot
		*out = make([]SearchableSnapshotObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetPriority != nil {
		in, out := &in.SetPriority, &out.SetPriority
		*out = make([]SetPriorityObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unfollow != nil {
		in, out := &in.Unfollow, &out.Unfollow
		*out = make([]UnfollowObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColdObservation.
func (in *ColdObservation) DeepCopy() *ColdObservation {
	if in == nil {
		return nil
	}
	out := new(ColdObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ColdParameters) DeepCopyInto(out *ColdParameters) {
	*out = *in
	if in.Allocate != nil {
		in, out := &in.Allocate, &out.Allocate
		*out = make([]AllocateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Downsample != nil {
		in, out := &in.Downsample, &out.Downsample
		*out = make([]DownsampleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Freeze != nil {
		in, out := &in.Freeze, &out.Freeze
		*out = make([]FreezeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = make([]MigrateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = make([]ReadonlyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SearchableSnapshot != nil {
		in, out := &in.SearchableSnapshot, &out.SearchableSnapshot
		*out = make([]SearchableSnapshotParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetPriority != nil {
		in, out := &in.SetPriority, &out.SetPriority
		*out = make([]SetPriorityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unfollow != nil {
		in, out := &in.Unfollow, &out.Unfollow
		*out = make([]UnfollowParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ColdParameters.
func (in *ColdParameters) DeepCopy() *ColdParameters {
	if in == nil {
		return nil
	}
	out := new(ColdParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteDeleteInitParameters) DeepCopyInto(out *DeleteDeleteInitParameters) {
	*out = *in
	if in.DeleteSearchableSnapshot != nil {
		in, out := &in.DeleteSearchableSnapshot, &out.DeleteSearchableSnapshot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteDeleteInitParameters.
func (in *DeleteDeleteInitParameters) DeepCopy() *DeleteDeleteInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeleteDeleteInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteDeleteObservation) DeepCopyInto(out *DeleteDeleteObservation) {
	*out = *in
	if in.DeleteSearchableSnapshot != nil {
		in, out := &in.DeleteSearchableSnapshot, &out.DeleteSearchableSnapshot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteDeleteObservation.
func (in *DeleteDeleteObservation) DeepCopy() *DeleteDeleteObservation {
	if in == nil {
		return nil
	}
	out := new(DeleteDeleteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteDeleteParameters) DeepCopyInto(out *DeleteDeleteParameters) {
	*out = *in
	if in.DeleteSearchableSnapshot != nil {
		in, out := &in.DeleteSearchableSnapshot, &out.DeleteSearchableSnapshot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteDeleteParameters.
func (in *DeleteDeleteParameters) DeepCopy() *DeleteDeleteParameters {
	if in == nil {
		return nil
	}
	out := new(DeleteDeleteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteInitParameters) DeepCopyInto(out *DeleteInitParameters) {
	*out = *in
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = make([]DeleteDeleteInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.WaitForSnapshot != nil {
		in, out := &in.WaitForSnapshot, &out.WaitForSnapshot
		*out = make([]WaitForSnapshotInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteInitParameters.
func (in *DeleteInitParameters) DeepCopy() *DeleteInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeleteInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteObservation) DeepCopyInto(out *DeleteObservation) {
	*out = *in
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = make([]DeleteDeleteObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.WaitForSnapshot != nil {
		in, out := &in.WaitForSnapshot, &out.WaitForSnapshot
		*out = make([]WaitForSnapshotObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteObservation.
func (in *DeleteObservation) DeepCopy() *DeleteObservation {
	if in == nil {
		return nil
	}
	out := new(DeleteObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeleteParameters) DeepCopyInto(out *DeleteParameters) {
	*out = *in
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = make([]DeleteDeleteParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.WaitForSnapshot != nil {
		in, out := &in.WaitForSnapshot, &out.WaitForSnapshot
		*out = make([]WaitForSnapshotParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeleteParameters.
func (in *DeleteParameters) DeepCopy() *DeleteParameters {
	if in == nil {
		return nil
	}
	out := new(DeleteParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownsampleInitParameters) DeepCopyInto(out *DownsampleInitParameters) {
	*out = *in
	if in.FixedInterval != nil {
		in, out := &in.FixedInterval, &out.FixedInterval
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownsampleInitParameters.
func (in *DownsampleInitParameters) DeepCopy() *DownsampleInitParameters {
	if in == nil {
		return nil
	}
	out := new(DownsampleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownsampleObservation) DeepCopyInto(out *DownsampleObservation) {
	*out = *in
	if in.FixedInterval != nil {
		in, out := &in.FixedInterval, &out.FixedInterval
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownsampleObservation.
func (in *DownsampleObservation) DeepCopy() *DownsampleObservation {
	if in == nil {
		return nil
	}
	out := new(DownsampleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownsampleParameters) DeepCopyInto(out *DownsampleParameters) {
	*out = *in
	if in.FixedInterval != nil {
		in, out := &in.FixedInterval, &out.FixedInterval
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownsampleParameters.
func (in *DownsampleParameters) DeepCopy() *DownsampleParameters {
	if in == nil {
		return nil
	}
	out := new(DownsampleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConnectionInitParameters) DeepCopyInto(out *ElasticsearchConnectionInitParameters) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EsClientAuthenticationSecretRef != nil {
		in, out := &in.EsClientAuthenticationSecretRef, &out.EsClientAuthenticationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyDataSecretRef != nil {
		in, out := &in.KeyDataSecretRef, &out.KeyDataSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConnectionInitParameters.
func (in *ElasticsearchConnectionInitParameters) DeepCopy() *ElasticsearchConnectionInitParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConnectionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConnectionObservation) DeepCopyInto(out *ElasticsearchConnectionObservation) {
	*out = *in
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConnectionObservation.
func (in *ElasticsearchConnectionObservation) DeepCopy() *ElasticsearchConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConnectionParameters) DeepCopyInto(out *ElasticsearchConnectionParameters) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.EndpointsSecretRef != nil {
		in, out := &in.EndpointsSecretRef, &out.EndpointsSecretRef
		*out = new([]v1.SecretKeySelector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.SecretKeySelector, len(*in))
			copy(*out, *in)
		}
	}
	if in.EsClientAuthenticationSecretRef != nil {
		in, out := &in.EsClientAuthenticationSecretRef, &out.EsClientAuthenticationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.HeadersSecretRef != nil {
		in, out := &in.HeadersSecretRef, &out.HeadersSecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyDataSecretRef != nil {
		in, out := &in.KeyDataSecretRef, &out.KeyDataSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConnectionParameters.
func (in *ElasticsearchConnectionParameters) DeepCopy() *ElasticsearchConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForcemergeInitParameters) DeepCopyInto(out *ForcemergeInitParameters) {
	*out = *in
	if in.IndexCodec != nil {
		in, out := &in.IndexCodec, &out.IndexCodec
		*out = new(string)
		**out = **in
	}
	if in.MaxNumSegments != nil {
		in, out := &in.MaxNumSegments, &out.MaxNumSegments
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForcemergeInitParameters.
func (in *ForcemergeInitParameters) DeepCopy() *ForcemergeInitParameters {
	if in == nil {
		return nil
	}
	out := new(ForcemergeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForcemergeObservation) DeepCopyInto(out *ForcemergeObservation) {
	*out = *in
	if in.IndexCodec != nil {
		in, out := &in.IndexCodec, &out.IndexCodec
		*out = new(string)
		**out = **in
	}
	if in.MaxNumSegments != nil {
		in, out := &in.MaxNumSegments, &out.MaxNumSegments
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForcemergeObservation.
func (in *ForcemergeObservation) DeepCopy() *ForcemergeObservation {
	if in == nil {
		return nil
	}
	out := new(ForcemergeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForcemergeParameters) DeepCopyInto(out *ForcemergeParameters) {
	*out = *in
	if in.IndexCodec != nil {
		in, out := &in.IndexCodec, &out.IndexCodec
		*out = new(string)
		**out = **in
	}
	if in.MaxNumSegments != nil {
		in, out := &in.MaxNumSegments, &out.MaxNumSegments
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForcemergeParameters.
func (in *ForcemergeParameters) DeepCopy() *ForcemergeParameters {
	if in == nil {
		return nil
	}
	out := new(ForcemergeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreezeInitParameters) DeepCopyInto(out *FreezeInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeInitParameters.
func (in *FreezeInitParameters) DeepCopy() *FreezeInitParameters {
	if in == nil {
		return nil
	}
	out := new(FreezeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreezeObservation) DeepCopyInto(out *FreezeObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeObservation.
func (in *FreezeObservation) DeepCopy() *FreezeObservation {
	if in == nil {
		return nil
	}
	out := new(FreezeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FreezeParameters) DeepCopyInto(out *FreezeParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FreezeParameters.
func (in *FreezeParameters) DeepCopy() *FreezeParameters {
	if in == nil {
		return nil
	}
	out := new(FreezeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrozenInitParameters) DeepCopyInto(out *FrozenInitParameters) {
	*out = *in
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.SearchableSnapshot != nil {
		in, out := &in.SearchableSnapshot, &out.SearchableSnapshot
		*out = make([]FrozenSearchableSnapshotInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrozenInitParameters.
func (in *FrozenInitParameters) DeepCopy() *FrozenInitParameters {
	if in == nil {
		return nil
	}
	out := new(FrozenInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrozenObservation) DeepCopyInto(out *FrozenObservation) {
	*out = *in
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.SearchableSnapshot != nil {
		in, out := &in.SearchableSnapshot, &out.SearchableSnapshot
		*out = make([]FrozenSearchableSnapshotObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrozenObservation.
func (in *FrozenObservation) DeepCopy() *FrozenObservation {
	if in == nil {
		return nil
	}
	out := new(FrozenObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrozenParameters) DeepCopyInto(out *FrozenParameters) {
	*out = *in
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.SearchableSnapshot != nil {
		in, out := &in.SearchableSnapshot, &out.SearchableSnapshot
		*out = make([]FrozenSearchableSnapshotParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrozenParameters.
func (in *FrozenParameters) DeepCopy() *FrozenParameters {
	if in == nil {
		return nil
	}
	out := new(FrozenParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrozenSearchableSnapshotInitParameters) DeepCopyInto(out *FrozenSearchableSnapshotInitParameters) {
	*out = *in
	if in.ForceMergeIndex != nil {
		in, out := &in.ForceMergeIndex, &out.ForceMergeIndex
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotRepository != nil {
		in, out := &in.SnapshotRepository, &out.SnapshotRepository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrozenSearchableSnapshotInitParameters.
func (in *FrozenSearchableSnapshotInitParameters) DeepCopy() *FrozenSearchableSnapshotInitParameters {
	if in == nil {
		return nil
	}
	out := new(FrozenSearchableSnapshotInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrozenSearchableSnapshotObservation) DeepCopyInto(out *FrozenSearchableSnapshotObservation) {
	*out = *in
	if in.ForceMergeIndex != nil {
		in, out := &in.ForceMergeIndex, &out.ForceMergeIndex
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotRepository != nil {
		in, out := &in.SnapshotRepository, &out.SnapshotRepository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrozenSearchableSnapshotObservation.
func (in *FrozenSearchableSnapshotObservation) DeepCopy() *FrozenSearchableSnapshotObservation {
	if in == nil {
		return nil
	}
	out := new(FrozenSearchableSnapshotObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FrozenSearchableSnapshotParameters) DeepCopyInto(out *FrozenSearchableSnapshotParameters) {
	*out = *in
	if in.ForceMergeIndex != nil {
		in, out := &in.ForceMergeIndex, &out.ForceMergeIndex
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotRepository != nil {
		in, out := &in.SnapshotRepository, &out.SnapshotRepository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FrozenSearchableSnapshotParameters.
func (in *FrozenSearchableSnapshotParameters) DeepCopy() *FrozenSearchableSnapshotParameters {
	if in == nil {
		return nil
	}
	out := new(FrozenSearchableSnapshotParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotDownsampleInitParameters) DeepCopyInto(out *HotDownsampleInitParameters) {
	*out = *in
	if in.FixedInterval != nil {
		in, out := &in.FixedInterval, &out.FixedInterval
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotDownsampleInitParameters.
func (in *HotDownsampleInitParameters) DeepCopy() *HotDownsampleInitParameters {
	if in == nil {
		return nil
	}
	out := new(HotDownsampleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotDownsampleObservation) DeepCopyInto(out *HotDownsampleObservation) {
	*out = *in
	if in.FixedInterval != nil {
		in, out := &in.FixedInterval, &out.FixedInterval
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotDownsampleObservation.
func (in *HotDownsampleObservation) DeepCopy() *HotDownsampleObservation {
	if in == nil {
		return nil
	}
	out := new(HotDownsampleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotDownsampleParameters) DeepCopyInto(out *HotDownsampleParameters) {
	*out = *in
	if in.FixedInterval != nil {
		in, out := &in.FixedInterval, &out.FixedInterval
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotDownsampleParameters.
func (in *HotDownsampleParameters) DeepCopy() *HotDownsampleParameters {
	if in == nil {
		return nil
	}
	out := new(HotDownsampleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotInitParameters) DeepCopyInto(out *HotInitParameters) {
	*out = *in
	if in.Downsample != nil {
		in, out := &in.Downsample, &out.Downsample
		*out = make([]HotDownsampleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Forcemerge != nil {
		in, out := &in.Forcemerge, &out.Forcemerge
		*out = make([]ForcemergeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = make([]HotReadonlyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rollover != nil {
		in, out := &in.Rollover, &out.Rollover
		*out = make([]RolloverInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SearchableSnapshot != nil {
		in, out := &in.SearchableSnapshot, &out.SearchableSnapshot
		*out = make([]HotSearchableSnapshotInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetPriority != nil {
		in, out := &in.SetPriority, &out.SetPriority
		*out = make([]HotSetPriorityInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Shrink != nil {
		in, out := &in.Shrink, &out.Shrink
		*out = make([]ShrinkInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unfollow != nil {
		in, out := &in.Unfollow, &out.Unfollow
		*out = make([]HotUnfollowInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotInitParameters.
func (in *HotInitParameters) DeepCopy() *HotInitParameters {
	if in == nil {
		return nil
	}
	out := new(HotInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotObservation) DeepCopyInto(out *HotObservation) {
	*out = *in
	if in.Downsample != nil {
		in, out := &in.Downsample, &out.Downsample
		*out = make([]HotDownsampleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Forcemerge != nil {
		in, out := &in.Forcemerge, &out.Forcemerge
		*out = make([]ForcemergeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = make([]HotReadonlyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rollover != nil {
		in, out := &in.Rollover, &out.Rollover
		*out = make([]RolloverObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SearchableSnapshot != nil {
		in, out := &in.SearchableSnapshot, &out.SearchableSnapshot
		*out = make([]HotSearchableSnapshotObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetPriority != nil {
		in, out := &in.SetPriority, &out.SetPriority
		*out = make([]HotSetPriorityObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Shrink != nil {
		in, out := &in.Shrink, &out.Shrink
		*out = make([]ShrinkObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unfollow != nil {
		in, out := &in.Unfollow, &out.Unfollow
		*out = make([]HotUnfollowObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotObservation.
func (in *HotObservation) DeepCopy() *HotObservation {
	if in == nil {
		return nil
	}
	out := new(HotObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotParameters) DeepCopyInto(out *HotParameters) {
	*out = *in
	if in.Downsample != nil {
		in, out := &in.Downsample, &out.Downsample
		*out = make([]HotDownsampleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Forcemerge != nil {
		in, out := &in.Forcemerge, &out.Forcemerge
		*out = make([]ForcemergeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = make([]HotReadonlyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rollover != nil {
		in, out := &in.Rollover, &out.Rollover
		*out = make([]RolloverParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SearchableSnapshot != nil {
		in, out := &in.SearchableSnapshot, &out.SearchableSnapshot
		*out = make([]HotSearchableSnapshotParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetPriority != nil {
		in, out := &in.SetPriority, &out.SetPriority
		*out = make([]HotSetPriorityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Shrink != nil {
		in, out := &in.Shrink, &out.Shrink
		*out = make([]ShrinkParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unfollow != nil {
		in, out := &in.Unfollow, &out.Unfollow
		*out = make([]HotUnfollowParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotParameters.
func (in *HotParameters) DeepCopy() *HotParameters {
	if in == nil {
		return nil
	}
	out := new(HotParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotReadonlyInitParameters) DeepCopyInto(out *HotReadonlyInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotReadonlyInitParameters.
func (in *HotReadonlyInitParameters) DeepCopy() *HotReadonlyInitParameters {
	if in == nil {
		return nil
	}
	out := new(HotReadonlyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotReadonlyObservation) DeepCopyInto(out *HotReadonlyObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotReadonlyObservation.
func (in *HotReadonlyObservation) DeepCopy() *HotReadonlyObservation {
	if in == nil {
		return nil
	}
	out := new(HotReadonlyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotReadonlyParameters) DeepCopyInto(out *HotReadonlyParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotReadonlyParameters.
func (in *HotReadonlyParameters) DeepCopy() *HotReadonlyParameters {
	if in == nil {
		return nil
	}
	out := new(HotReadonlyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotSearchableSnapshotInitParameters) DeepCopyInto(out *HotSearchableSnapshotInitParameters) {
	*out = *in
	if in.ForceMergeIndex != nil {
		in, out := &in.ForceMergeIndex, &out.ForceMergeIndex
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotRepository != nil {
		in, out := &in.SnapshotRepository, &out.SnapshotRepository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotSearchableSnapshotInitParameters.
func (in *HotSearchableSnapshotInitParameters) DeepCopy() *HotSearchableSnapshotInitParameters {
	if in == nil {
		return nil
	}
	out := new(HotSearchableSnapshotInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotSearchableSnapshotObservation) DeepCopyInto(out *HotSearchableSnapshotObservation) {
	*out = *in
	if in.ForceMergeIndex != nil {
		in, out := &in.ForceMergeIndex, &out.ForceMergeIndex
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotRepository != nil {
		in, out := &in.SnapshotRepository, &out.SnapshotRepository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotSearchableSnapshotObservation.
func (in *HotSearchableSnapshotObservation) DeepCopy() *HotSearchableSnapshotObservation {
	if in == nil {
		return nil
	}
	out := new(HotSearchableSnapshotObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotSearchableSnapshotParameters) DeepCopyInto(out *HotSearchableSnapshotParameters) {
	*out = *in
	if in.ForceMergeIndex != nil {
		in, out := &in.ForceMergeIndex, &out.ForceMergeIndex
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotRepository != nil {
		in, out := &in.SnapshotRepository, &out.SnapshotRepository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotSearchableSnapshotParameters.
func (in *HotSearchableSnapshotParameters) DeepCopy() *HotSearchableSnapshotParameters {
	if in == nil {
		return nil
	}
	out := new(HotSearchableSnapshotParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotSetPriorityInitParameters) DeepCopyInto(out *HotSetPriorityInitParameters) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotSetPriorityInitParameters.
func (in *HotSetPriorityInitParameters) DeepCopy() *HotSetPriorityInitParameters {
	if in == nil {
		return nil
	}
	out := new(HotSetPriorityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotSetPriorityObservation) DeepCopyInto(out *HotSetPriorityObservation) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotSetPriorityObservation.
func (in *HotSetPriorityObservation) DeepCopy() *HotSetPriorityObservation {
	if in == nil {
		return nil
	}
	out := new(HotSetPriorityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotSetPriorityParameters) DeepCopyInto(out *HotSetPriorityParameters) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotSetPriorityParameters.
func (in *HotSetPriorityParameters) DeepCopy() *HotSetPriorityParameters {
	if in == nil {
		return nil
	}
	out := new(HotSetPriorityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotUnfollowInitParameters) DeepCopyInto(out *HotUnfollowInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotUnfollowInitParameters.
func (in *HotUnfollowInitParameters) DeepCopy() *HotUnfollowInitParameters {
	if in == nil {
		return nil
	}
	out := new(HotUnfollowInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotUnfollowObservation) DeepCopyInto(out *HotUnfollowObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotUnfollowObservation.
func (in *HotUnfollowObservation) DeepCopy() *HotUnfollowObservation {
	if in == nil {
		return nil
	}
	out := new(HotUnfollowObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HotUnfollowParameters) DeepCopyInto(out *HotUnfollowParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HotUnfollowParameters.
func (in *HotUnfollowParameters) DeepCopy() *HotUnfollowParameters {
	if in == nil {
		return nil
	}
	out := new(HotUnfollowParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexLifecycle) DeepCopyInto(out *IndexLifecycle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexLifecycle.
func (in *IndexLifecycle) DeepCopy() *IndexLifecycle {
	if in == nil {
		return nil
	}
	out := new(IndexLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IndexLifecycle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexLifecycleInitParameters) DeepCopyInto(out *IndexLifecycleInitParameters) {
	*out = *in
	if in.Cold != nil {
		in, out := &in.Cold, &out.Cold
		*out = make([]ColdInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = make([]DeleteInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]ElasticsearchConnectionInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Frozen != nil {
		in, out := &in.Frozen, &out.Frozen
		*out = make([]FrozenInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hot != nil {
		in, out := &in.Hot, &out.Hot
		*out = make([]HotInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.Warm != nil {
		in, out := &in.Warm, &out.Warm
		*out = make([]WarmInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexLifecycleInitParameters.
func (in *IndexLifecycleInitParameters) DeepCopy() *IndexLifecycleInitParameters {
	if in == nil {
		return nil
	}
	out := new(IndexLifecycleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexLifecycleList) DeepCopyInto(out *IndexLifecycleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IndexLifecycle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexLifecycleList.
func (in *IndexLifecycleList) DeepCopy() *IndexLifecycleList {
	if in == nil {
		return nil
	}
	out := new(IndexLifecycleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IndexLifecycleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexLifecycleObservation) DeepCopyInto(out *IndexLifecycleObservation) {
	*out = *in
	if in.Cold != nil {
		in, out := &in.Cold, &out.Cold
		*out = make([]ColdObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = make([]DeleteObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]ElasticsearchConnectionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Frozen != nil {
		in, out := &in.Frozen, &out.Frozen
		*out = make([]FrozenObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hot != nil {
		in, out := &in.Hot, &out.Hot
		*out = make([]HotObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.ModifiedDate != nil {
		in, out := &in.ModifiedDate, &out.ModifiedDate
		*out = new(string)
		**out = **in
	}
	if in.Warm != nil {
		in, out := &in.Warm, &out.Warm
		*out = make([]WarmObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexLifecycleObservation.
func (in *IndexLifecycleObservation) DeepCopy() *IndexLifecycleObservation {
	if in == nil {
		return nil
	}
	out := new(IndexLifecycleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexLifecycleParameters) DeepCopyInto(out *IndexLifecycleParameters) {
	*out = *in
	if in.Cold != nil {
		in, out := &in.Cold, &out.Cold
		*out = make([]ColdParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = make([]DeleteParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]ElasticsearchConnectionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Frozen != nil {
		in, out := &in.Frozen, &out.Frozen
		*out = make([]FrozenParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hot != nil {
		in, out := &in.Hot, &out.Hot
		*out = make([]HotParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.Warm != nil {
		in, out := &in.Warm, &out.Warm
		*out = make([]WarmParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexLifecycleParameters.
func (in *IndexLifecycleParameters) DeepCopy() *IndexLifecycleParameters {
	if in == nil {
		return nil
	}
	out := new(IndexLifecycleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexLifecycleSpec) DeepCopyInto(out *IndexLifecycleSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexLifecycleSpec.
func (in *IndexLifecycleSpec) DeepCopy() *IndexLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(IndexLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IndexLifecycleStatus) DeepCopyInto(out *IndexLifecycleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IndexLifecycleStatus.
func (in *IndexLifecycleStatus) DeepCopy() *IndexLifecycleStatus {
	if in == nil {
		return nil
	}
	out := new(IndexLifecycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrateInitParameters) DeepCopyInto(out *MigrateInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrateInitParameters.
func (in *MigrateInitParameters) DeepCopy() *MigrateInitParameters {
	if in == nil {
		return nil
	}
	out := new(MigrateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrateObservation) DeepCopyInto(out *MigrateObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrateObservation.
func (in *MigrateObservation) DeepCopy() *MigrateObservation {
	if in == nil {
		return nil
	}
	out := new(MigrateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MigrateParameters) DeepCopyInto(out *MigrateParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MigrateParameters.
func (in *MigrateParameters) DeepCopy() *MigrateParameters {
	if in == nil {
		return nil
	}
	out := new(MigrateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadonlyInitParameters) DeepCopyInto(out *ReadonlyInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadonlyInitParameters.
func (in *ReadonlyInitParameters) DeepCopy() *ReadonlyInitParameters {
	if in == nil {
		return nil
	}
	out := new(ReadonlyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadonlyObservation) DeepCopyInto(out *ReadonlyObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadonlyObservation.
func (in *ReadonlyObservation) DeepCopy() *ReadonlyObservation {
	if in == nil {
		return nil
	}
	out := new(ReadonlyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadonlyParameters) DeepCopyInto(out *ReadonlyParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadonlyParameters.
func (in *ReadonlyParameters) DeepCopy() *ReadonlyParameters {
	if in == nil {
		return nil
	}
	out := new(ReadonlyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloverInitParameters) DeepCopyInto(out *RolloverInitParameters) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(string)
		**out = **in
	}
	if in.MaxDocs != nil {
		in, out := &in.MaxDocs, &out.MaxDocs
		*out = new(float64)
		**out = **in
	}
	if in.MaxPrimaryShardDocs != nil {
		in, out := &in.MaxPrimaryShardDocs, &out.MaxPrimaryShardDocs
		*out = new(float64)
		**out = **in
	}
	if in.MaxPrimaryShardSize != nil {
		in, out := &in.MaxPrimaryShardSize, &out.MaxPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(string)
		**out = **in
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.MinDocs != nil {
		in, out := &in.MinDocs, &out.MinDocs
		*out = new(float64)
		**out = **in
	}
	if in.MinPrimaryShardDocs != nil {
		in, out := &in.MinPrimaryShardDocs, &out.MinPrimaryShardDocs
		*out = new(float64)
		**out = **in
	}
	if in.MinPrimaryShardSize != nil {
		in, out := &in.MinPrimaryShardSize, &out.MinPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloverInitParameters.
func (in *RolloverInitParameters) DeepCopy() *RolloverInitParameters {
	if in == nil {
		return nil
	}
	out := new(RolloverInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloverObservation) DeepCopyInto(out *RolloverObservation) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(string)
		**out = **in
	}
	if in.MaxDocs != nil {
		in, out := &in.MaxDocs, &out.MaxDocs
		*out = new(float64)
		**out = **in
	}
	if in.MaxPrimaryShardDocs != nil {
		in, out := &in.MaxPrimaryShardDocs, &out.MaxPrimaryShardDocs
		*out = new(float64)
		**out = **in
	}
	if in.MaxPrimaryShardSize != nil {
		in, out := &in.MaxPrimaryShardSize, &out.MaxPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(string)
		**out = **in
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.MinDocs != nil {
		in, out := &in.MinDocs, &out.MinDocs
		*out = new(float64)
		**out = **in
	}
	if in.MinPrimaryShardDocs != nil {
		in, out := &in.MinPrimaryShardDocs, &out.MinPrimaryShardDocs
		*out = new(float64)
		**out = **in
	}
	if in.MinPrimaryShardSize != nil {
		in, out := &in.MinPrimaryShardSize, &out.MinPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloverObservation.
func (in *RolloverObservation) DeepCopy() *RolloverObservation {
	if in == nil {
		return nil
	}
	out := new(RolloverObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloverParameters) DeepCopyInto(out *RolloverParameters) {
	*out = *in
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(string)
		**out = **in
	}
	if in.MaxDocs != nil {
		in, out := &in.MaxDocs, &out.MaxDocs
		*out = new(float64)
		**out = **in
	}
	if in.MaxPrimaryShardDocs != nil {
		in, out := &in.MaxPrimaryShardDocs, &out.MaxPrimaryShardDocs
		*out = new(float64)
		**out = **in
	}
	if in.MaxPrimaryShardSize != nil {
		in, out := &in.MaxPrimaryShardSize, &out.MaxPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		*out = new(string)
		**out = **in
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.MinDocs != nil {
		in, out := &in.MinDocs, &out.MinDocs
		*out = new(float64)
		**out = **in
	}
	if in.MinPrimaryShardDocs != nil {
		in, out := &in.MinPrimaryShardDocs, &out.MinPrimaryShardDocs
		*out = new(float64)
		**out = **in
	}
	if in.MinPrimaryShardSize != nil {
		in, out := &in.MinPrimaryShardSize, &out.MinPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloverParameters.
func (in *RolloverParameters) DeepCopy() *RolloverParameters {
	if in == nil {
		return nil
	}
	out := new(RolloverParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchableSnapshotInitParameters) DeepCopyInto(out *SearchableSnapshotInitParameters) {
	*out = *in
	if in.ForceMergeIndex != nil {
		in, out := &in.ForceMergeIndex, &out.ForceMergeIndex
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotRepository != nil {
		in, out := &in.SnapshotRepository, &out.SnapshotRepository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchableSnapshotInitParameters.
func (in *SearchableSnapshotInitParameters) DeepCopy() *SearchableSnapshotInitParameters {
	if in == nil {
		return nil
	}
	out := new(SearchableSnapshotInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchableSnapshotObservation) DeepCopyInto(out *SearchableSnapshotObservation) {
	*out = *in
	if in.ForceMergeIndex != nil {
		in, out := &in.ForceMergeIndex, &out.ForceMergeIndex
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotRepository != nil {
		in, out := &in.SnapshotRepository, &out.SnapshotRepository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchableSnapshotObservation.
func (in *SearchableSnapshotObservation) DeepCopy() *SearchableSnapshotObservation {
	if in == nil {
		return nil
	}
	out := new(SearchableSnapshotObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SearchableSnapshotParameters) DeepCopyInto(out *SearchableSnapshotParameters) {
	*out = *in
	if in.ForceMergeIndex != nil {
		in, out := &in.ForceMergeIndex, &out.ForceMergeIndex
		*out = new(bool)
		**out = **in
	}
	if in.SnapshotRepository != nil {
		in, out := &in.SnapshotRepository, &out.SnapshotRepository
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SearchableSnapshotParameters.
func (in *SearchableSnapshotParameters) DeepCopy() *SearchableSnapshotParameters {
	if in == nil {
		return nil
	}
	out := new(SearchableSnapshotParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetPriorityInitParameters) DeepCopyInto(out *SetPriorityInitParameters) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetPriorityInitParameters.
func (in *SetPriorityInitParameters) DeepCopy() *SetPriorityInitParameters {
	if in == nil {
		return nil
	}
	out := new(SetPriorityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetPriorityObservation) DeepCopyInto(out *SetPriorityObservation) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetPriorityObservation.
func (in *SetPriorityObservation) DeepCopy() *SetPriorityObservation {
	if in == nil {
		return nil
	}
	out := new(SetPriorityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SetPriorityParameters) DeepCopyInto(out *SetPriorityParameters) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SetPriorityParameters.
func (in *SetPriorityParameters) DeepCopy() *SetPriorityParameters {
	if in == nil {
		return nil
	}
	out := new(SetPriorityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShrinkInitParameters) DeepCopyInto(out *ShrinkInitParameters) {
	*out = *in
	if in.AllowWriteAfterShrink != nil {
		in, out := &in.AllowWriteAfterShrink, &out.AllowWriteAfterShrink
		*out = new(bool)
		**out = **in
	}
	if in.MaxPrimaryShardSize != nil {
		in, out := &in.MaxPrimaryShardSize, &out.MaxPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.NumberOfShards != nil {
		in, out := &in.NumberOfShards, &out.NumberOfShards
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShrinkInitParameters.
func (in *ShrinkInitParameters) DeepCopy() *ShrinkInitParameters {
	if in == nil {
		return nil
	}
	out := new(ShrinkInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShrinkObservation) DeepCopyInto(out *ShrinkObservation) {
	*out = *in
	if in.AllowWriteAfterShrink != nil {
		in, out := &in.AllowWriteAfterShrink, &out.AllowWriteAfterShrink
		*out = new(bool)
		**out = **in
	}
	if in.MaxPrimaryShardSize != nil {
		in, out := &in.MaxPrimaryShardSize, &out.MaxPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.NumberOfShards != nil {
		in, out := &in.NumberOfShards, &out.NumberOfShards
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShrinkObservation.
func (in *ShrinkObservation) DeepCopy() *ShrinkObservation {
	if in == nil {
		return nil
	}
	out := new(ShrinkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShrinkParameters) DeepCopyInto(out *ShrinkParameters) {
	*out = *in
	if in.AllowWriteAfterShrink != nil {
		in, out := &in.AllowWriteAfterShrink, &out.AllowWriteAfterShrink
		*out = new(bool)
		**out = **in
	}
	if in.MaxPrimaryShardSize != nil {
		in, out := &in.MaxPrimaryShardSize, &out.MaxPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.NumberOfShards != nil {
		in, out := &in.NumberOfShards, &out.NumberOfShards
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShrinkParameters.
func (in *ShrinkParameters) DeepCopy() *ShrinkParameters {
	if in == nil {
		return nil
	}
	out := new(ShrinkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnfollowInitParameters) DeepCopyInto(out *UnfollowInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnfollowInitParameters.
func (in *UnfollowInitParameters) DeepCopy() *UnfollowInitParameters {
	if in == nil {
		return nil
	}
	out := new(UnfollowInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnfollowObservation) DeepCopyInto(out *UnfollowObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnfollowObservation.
func (in *UnfollowObservation) DeepCopy() *UnfollowObservation {
	if in == nil {
		return nil
	}
	out := new(UnfollowObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnfollowParameters) DeepCopyInto(out *UnfollowParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnfollowParameters.
func (in *UnfollowParameters) DeepCopy() *UnfollowParameters {
	if in == nil {
		return nil
	}
	out := new(UnfollowParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForSnapshotInitParameters) DeepCopyInto(out *WaitForSnapshotInitParameters) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForSnapshotInitParameters.
func (in *WaitForSnapshotInitParameters) DeepCopy() *WaitForSnapshotInitParameters {
	if in == nil {
		return nil
	}
	out := new(WaitForSnapshotInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForSnapshotObservation) DeepCopyInto(out *WaitForSnapshotObservation) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForSnapshotObservation.
func (in *WaitForSnapshotObservation) DeepCopy() *WaitForSnapshotObservation {
	if in == nil {
		return nil
	}
	out := new(WaitForSnapshotObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitForSnapshotParameters) DeepCopyInto(out *WaitForSnapshotParameters) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitForSnapshotParameters.
func (in *WaitForSnapshotParameters) DeepCopy() *WaitForSnapshotParameters {
	if in == nil {
		return nil
	}
	out := new(WaitForSnapshotParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmAllocateInitParameters) DeepCopyInto(out *WarmAllocateInitParameters) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(string)
		**out = **in
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(string)
		**out = **in
	}
	if in.NumberOfReplicas != nil {
		in, out := &in.NumberOfReplicas, &out.NumberOfReplicas
		*out = new(float64)
		**out = **in
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = new(string)
		**out = **in
	}
	if in.TotalShardsPerNode != nil {
		in, out := &in.TotalShardsPerNode, &out.TotalShardsPerNode
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmAllocateInitParameters.
func (in *WarmAllocateInitParameters) DeepCopy() *WarmAllocateInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarmAllocateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmAllocateObservation) DeepCopyInto(out *WarmAllocateObservation) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(string)
		**out = **in
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(string)
		**out = **in
	}
	if in.NumberOfReplicas != nil {
		in, out := &in.NumberOfReplicas, &out.NumberOfReplicas
		*out = new(float64)
		**out = **in
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = new(string)
		**out = **in
	}
	if in.TotalShardsPerNode != nil {
		in, out := &in.TotalShardsPerNode, &out.TotalShardsPerNode
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmAllocateObservation.
func (in *WarmAllocateObservation) DeepCopy() *WarmAllocateObservation {
	if in == nil {
		return nil
	}
	out := new(WarmAllocateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmAllocateParameters) DeepCopyInto(out *WarmAllocateParameters) {
	*out = *in
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = new(string)
		**out = **in
	}
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = new(string)
		**out = **in
	}
	if in.NumberOfReplicas != nil {
		in, out := &in.NumberOfReplicas, &out.NumberOfReplicas
		*out = new(float64)
		**out = **in
	}
	if in.Require != nil {
		in, out := &in.Require, &out.Require
		*out = new(string)
		**out = **in
	}
	if in.TotalShardsPerNode != nil {
		in, out := &in.TotalShardsPerNode, &out.TotalShardsPerNode
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmAllocateParameters.
func (in *WarmAllocateParameters) DeepCopy() *WarmAllocateParameters {
	if in == nil {
		return nil
	}
	out := new(WarmAllocateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmDownsampleInitParameters) DeepCopyInto(out *WarmDownsampleInitParameters) {
	*out = *in
	if in.FixedInterval != nil {
		in, out := &in.FixedInterval, &out.FixedInterval
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmDownsampleInitParameters.
func (in *WarmDownsampleInitParameters) DeepCopy() *WarmDownsampleInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarmDownsampleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmDownsampleObservation) DeepCopyInto(out *WarmDownsampleObservation) {
	*out = *in
	if in.FixedInterval != nil {
		in, out := &in.FixedInterval, &out.FixedInterval
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmDownsampleObservation.
func (in *WarmDownsampleObservation) DeepCopy() *WarmDownsampleObservation {
	if in == nil {
		return nil
	}
	out := new(WarmDownsampleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmDownsampleParameters) DeepCopyInto(out *WarmDownsampleParameters) {
	*out = *in
	if in.FixedInterval != nil {
		in, out := &in.FixedInterval, &out.FixedInterval
		*out = new(string)
		**out = **in
	}
	if in.WaitTimeout != nil {
		in, out := &in.WaitTimeout, &out.WaitTimeout
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmDownsampleParameters.
func (in *WarmDownsampleParameters) DeepCopy() *WarmDownsampleParameters {
	if in == nil {
		return nil
	}
	out := new(WarmDownsampleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmForcemergeInitParameters) DeepCopyInto(out *WarmForcemergeInitParameters) {
	*out = *in
	if in.IndexCodec != nil {
		in, out := &in.IndexCodec, &out.IndexCodec
		*out = new(string)
		**out = **in
	}
	if in.MaxNumSegments != nil {
		in, out := &in.MaxNumSegments, &out.MaxNumSegments
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmForcemergeInitParameters.
func (in *WarmForcemergeInitParameters) DeepCopy() *WarmForcemergeInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarmForcemergeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmForcemergeObservation) DeepCopyInto(out *WarmForcemergeObservation) {
	*out = *in
	if in.IndexCodec != nil {
		in, out := &in.IndexCodec, &out.IndexCodec
		*out = new(string)
		**out = **in
	}
	if in.MaxNumSegments != nil {
		in, out := &in.MaxNumSegments, &out.MaxNumSegments
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmForcemergeObservation.
func (in *WarmForcemergeObservation) DeepCopy() *WarmForcemergeObservation {
	if in == nil {
		return nil
	}
	out := new(WarmForcemergeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmForcemergeParameters) DeepCopyInto(out *WarmForcemergeParameters) {
	*out = *in
	if in.IndexCodec != nil {
		in, out := &in.IndexCodec, &out.IndexCodec
		*out = new(string)
		**out = **in
	}
	if in.MaxNumSegments != nil {
		in, out := &in.MaxNumSegments, &out.MaxNumSegments
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmForcemergeParameters.
func (in *WarmForcemergeParameters) DeepCopy() *WarmForcemergeParameters {
	if in == nil {
		return nil
	}
	out := new(WarmForcemergeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmInitParameters) DeepCopyInto(out *WarmInitParameters) {
	*out = *in
	if in.Allocate != nil {
		in, out := &in.Allocate, &out.Allocate
		*out = make([]WarmAllocateInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Downsample != nil {
		in, out := &in.Downsample, &out.Downsample
		*out = make([]WarmDownsampleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Forcemerge != nil {
		in, out := &in.Forcemerge, &out.Forcemerge
		*out = make([]WarmForcemergeInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = make([]WarmMigrateInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = make([]WarmReadonlyInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetPriority != nil {
		in, out := &in.SetPriority, &out.SetPriority
		*out = make([]WarmSetPriorityInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Shrink != nil {
		in, out := &in.Shrink, &out.Shrink
		*out = make([]WarmShrinkInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unfollow != nil {
		in, out := &in.Unfollow, &out.Unfollow
		*out = make([]WarmUnfollowInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmInitParameters.
func (in *WarmInitParameters) DeepCopy() *WarmInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarmInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmMigrateInitParameters) DeepCopyInto(out *WarmMigrateInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmMigrateInitParameters.
func (in *WarmMigrateInitParameters) DeepCopy() *WarmMigrateInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarmMigrateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmMigrateObservation) DeepCopyInto(out *WarmMigrateObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmMigrateObservation.
func (in *WarmMigrateObservation) DeepCopy() *WarmMigrateObservation {
	if in == nil {
		return nil
	}
	out := new(WarmMigrateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmMigrateParameters) DeepCopyInto(out *WarmMigrateParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmMigrateParameters.
func (in *WarmMigrateParameters) DeepCopy() *WarmMigrateParameters {
	if in == nil {
		return nil
	}
	out := new(WarmMigrateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmObservation) DeepCopyInto(out *WarmObservation) {
	*out = *in
	if in.Allocate != nil {
		in, out := &in.Allocate, &out.Allocate
		*out = make([]WarmAllocateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Downsample != nil {
		in, out := &in.Downsample, &out.Downsample
		*out = make([]WarmDownsampleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Forcemerge != nil {
		in, out := &in.Forcemerge, &out.Forcemerge
		*out = make([]WarmForcemergeObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = make([]WarmMigrateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = make([]WarmReadonlyObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetPriority != nil {
		in, out := &in.SetPriority, &out.SetPriority
		*out = make([]WarmSetPriorityObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Shrink != nil {
		in, out := &in.Shrink, &out.Shrink
		*out = make([]WarmShrinkObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unfollow != nil {
		in, out := &in.Unfollow, &out.Unfollow
		*out = make([]WarmUnfollowObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmObservation.
func (in *WarmObservation) DeepCopy() *WarmObservation {
	if in == nil {
		return nil
	}
	out := new(WarmObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmParameters) DeepCopyInto(out *WarmParameters) {
	*out = *in
	if in.Allocate != nil {
		in, out := &in.Allocate, &out.Allocate
		*out = make([]WarmAllocateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Downsample != nil {
		in, out := &in.Downsample, &out.Downsample
		*out = make([]WarmDownsampleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Forcemerge != nil {
		in, out := &in.Forcemerge, &out.Forcemerge
		*out = make([]WarmForcemergeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Migrate != nil {
		in, out := &in.Migrate, &out.Migrate
		*out = make([]WarmMigrateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MinAge != nil {
		in, out := &in.MinAge, &out.MinAge
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = make([]WarmReadonlyParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SetPriority != nil {
		in, out := &in.SetPriority, &out.SetPriority
		*out = make([]WarmSetPriorityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Shrink != nil {
		in, out := &in.Shrink, &out.Shrink
		*out = make([]WarmShrinkParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Unfollow != nil {
		in, out := &in.Unfollow, &out.Unfollow
		*out = make([]WarmUnfollowParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmParameters.
func (in *WarmParameters) DeepCopy() *WarmParameters {
	if in == nil {
		return nil
	}
	out := new(WarmParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmReadonlyInitParameters) DeepCopyInto(out *WarmReadonlyInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmReadonlyInitParameters.
func (in *WarmReadonlyInitParameters) DeepCopy() *WarmReadonlyInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarmReadonlyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmReadonlyObservation) DeepCopyInto(out *WarmReadonlyObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmReadonlyObservation.
func (in *WarmReadonlyObservation) DeepCopy() *WarmReadonlyObservation {
	if in == nil {
		return nil
	}
	out := new(WarmReadonlyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmReadonlyParameters) DeepCopyInto(out *WarmReadonlyParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmReadonlyParameters.
func (in *WarmReadonlyParameters) DeepCopy() *WarmReadonlyParameters {
	if in == nil {
		return nil
	}
	out := new(WarmReadonlyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmSetPriorityInitParameters) DeepCopyInto(out *WarmSetPriorityInitParameters) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmSetPriorityInitParameters.
func (in *WarmSetPriorityInitParameters) DeepCopy() *WarmSetPriorityInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarmSetPriorityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmSetPriorityObservation) DeepCopyInto(out *WarmSetPriorityObservation) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmSetPriorityObservation.
func (in *WarmSetPriorityObservation) DeepCopy() *WarmSetPriorityObservation {
	if in == nil {
		return nil
	}
	out := new(WarmSetPriorityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmSetPriorityParameters) DeepCopyInto(out *WarmSetPriorityParameters) {
	*out = *in
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmSetPriorityParameters.
func (in *WarmSetPriorityParameters) DeepCopy() *WarmSetPriorityParameters {
	if in == nil {
		return nil
	}
	out := new(WarmSetPriorityParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmShrinkInitParameters) DeepCopyInto(out *WarmShrinkInitParameters) {
	*out = *in
	if in.AllowWriteAfterShrink != nil {
		in, out := &in.AllowWriteAfterShrink, &out.AllowWriteAfterShrink
		*out = new(bool)
		**out = **in
	}
	if in.MaxPrimaryShardSize != nil {
		in, out := &in.MaxPrimaryShardSize, &out.MaxPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.NumberOfShards != nil {
		in, out := &in.NumberOfShards, &out.NumberOfShards
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmShrinkInitParameters.
func (in *WarmShrinkInitParameters) DeepCopy() *WarmShrinkInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarmShrinkInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmShrinkObservation) DeepCopyInto(out *WarmShrinkObservation) {
	*out = *in
	if in.AllowWriteAfterShrink != nil {
		in, out := &in.AllowWriteAfterShrink, &out.AllowWriteAfterShrink
		*out = new(bool)
		**out = **in
	}
	if in.MaxPrimaryShardSize != nil {
		in, out := &in.MaxPrimaryShardSize, &out.MaxPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.NumberOfShards != nil {
		in, out := &in.NumberOfShards, &out.NumberOfShards
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmShrinkObservation.
func (in *WarmShrinkObservation) DeepCopy() *WarmShrinkObservation {
	if in == nil {
		return nil
	}
	out := new(WarmShrinkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmShrinkParameters) DeepCopyInto(out *WarmShrinkParameters) {
	*out = *in
	if in.AllowWriteAfterShrink != nil {
		in, out := &in.AllowWriteAfterShrink, &out.AllowWriteAfterShrink
		*out = new(bool)
		**out = **in
	}
	if in.MaxPrimaryShardSize != nil {
		in, out := &in.MaxPrimaryShardSize, &out.MaxPrimaryShardSize
		*out = new(string)
		**out = **in
	}
	if in.NumberOfShards != nil {
		in, out := &in.NumberOfShards, &out.NumberOfShards
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmShrinkParameters.
func (in *WarmShrinkParameters) DeepCopy() *WarmShrinkParameters {
	if in == nil {
		return nil
	}
	out := new(WarmShrinkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmUnfollowInitParameters) DeepCopyInto(out *WarmUnfollowInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmUnfollowInitParameters.
func (in *WarmUnfollowInitParameters) DeepCopy() *WarmUnfollowInitParameters {
	if in == nil {
		return nil
	}
	out := new(WarmUnfollowInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmUnfollowObservation) DeepCopyInto(out *WarmUnfollowObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmUnfollowObservation.
func (in *WarmUnfollowObservation) DeepCopy() *WarmUnfollowObservation {
	if in == nil {
		return nil
	}
	out := new(WarmUnfollowObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WarmUnfollowParameters) DeepCopyInto(out *WarmUnfollowParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WarmUnfollowParameters.
func (in *WarmUnfollowParameters) DeepCopy() *WarmUnfollowParameters {
	if in == nil {
		return nil
	}
	out := new(WarmUnfollowParameters)
	in.DeepCopyInto(out)
	return out
}
