//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSettings) DeepCopyInto(out *ClusterSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSettings.
func (in *ClusterSettings) DeepCopy() *ClusterSettings {
	if in == nil {
		return nil
	}
	out := new(ClusterSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSettingsInitParameters) DeepCopyInto(out *ClusterSettingsInitParameters) {
	*out = *in
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]ElasticsearchConnectionInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Persistent != nil {
		in, out := &in.Persistent, &out.Persistent
		*out = make([]PersistentInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Transient != nil {
		in, out := &in.Transient, &out.Transient
		*out = make([]TransientInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSettingsInitParameters.
func (in *ClusterSettingsInitParameters) DeepCopy() *ClusterSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSettingsList) DeepCopyInto(out *ClusterSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSettingsList.
func (in *ClusterSettingsList) DeepCopy() *ClusterSettingsList {
	if in == nil {
		return nil
	}
	out := new(ClusterSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSettingsObservation) DeepCopyInto(out *ClusterSettingsObservation) {
	*out = *in
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]ElasticsearchConnectionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Persistent != nil {
		in, out := &in.Persistent, &out.Persistent
		*out = make([]PersistentObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Transient != nil {
		in, out := &in.Transient, &out.Transient
		*out = make([]TransientObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSettingsObservation.
func (in *ClusterSettingsObservation) DeepCopy() *ClusterSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(ClusterSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSettingsParameters) DeepCopyInto(out *ClusterSettingsParameters) {
	*out = *in
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]ElasticsearchConnectionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Persistent != nil {
		in, out := &in.Persistent, &out.Persistent
		*out = make([]PersistentParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Transient != nil {
		in, out := &in.Transient, &out.Transient
		*out = make([]TransientParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSettingsParameters.
func (in *ClusterSettingsParameters) DeepCopy() *ClusterSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(ClusterSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSettingsSpec) DeepCopyInto(out *ClusterSettingsSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSettingsSpec.
func (in *ClusterSettingsSpec) DeepCopy() *ClusterSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSettingsStatus) DeepCopyInto(out *ClusterSettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSettingsStatus.
func (in *ClusterSettingsStatus) DeepCopy() *ClusterSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterSettingsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConnectionInitParameters) DeepCopyInto(out *ElasticsearchConnectionInitParameters) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EsClientAuthenticationSecretRef != nil {
		in, out := &in.EsClientAuthenticationSecretRef, &out.EsClientAuthenticationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyDataSecretRef != nil {
		in, out := &in.KeyDataSecretRef, &out.KeyDataSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConnectionInitParameters.
func (in *ElasticsearchConnectionInitParameters) DeepCopy() *ElasticsearchConnectionInitParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConnectionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConnectionObservation) DeepCopyInto(out *ElasticsearchConnectionObservation) {
	*out = *in
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConnectionObservation.
func (in *ElasticsearchConnectionObservation) DeepCopy() *ElasticsearchConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConnectionParameters) DeepCopyInto(out *ElasticsearchConnectionParameters) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.EndpointsSecretRef != nil {
		in, out := &in.EndpointsSecretRef, &out.EndpointsSecretRef
		*out = new([]v1.SecretKeySelector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.SecretKeySelector, len(*in))
			copy(*out, *in)
		}
	}
	if in.EsClientAuthenticationSecretRef != nil {
		in, out := &in.EsClientAuthenticationSecretRef, &out.EsClientAuthenticationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.HeadersSecretRef != nil {
		in, out := &in.HeadersSecretRef, &out.HeadersSecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyDataSecretRef != nil {
		in, out := &in.KeyDataSecretRef, &out.KeyDataSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConnectionParameters.
func (in *ElasticsearchConnectionParameters) DeepCopy() *ElasticsearchConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentInitParameters) DeepCopyInto(out *PersistentInitParameters) {
	*out = *in
	if in.Setting != nil {
		in, out := &in.Setting, &out.Setting
		*out = make([]SettingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentInitParameters.
func (in *PersistentInitParameters) DeepCopy() *PersistentInitParameters {
	if in == nil {
		return nil
	}
	out := new(PersistentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentObservation) DeepCopyInto(out *PersistentObservation) {
	*out = *in
	if in.Setting != nil {
		in, out := &in.Setting, &out.Setting
		*out = make([]SettingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentObservation.
func (in *PersistentObservation) DeepCopy() *PersistentObservation {
	if in == nil {
		return nil
	}
	out := new(PersistentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentParameters) DeepCopyInto(out *PersistentParameters) {
	*out = *in
	if in.Setting != nil {
		in, out := &in.Setting, &out.Setting
		*out = make([]SettingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentParameters.
func (in *PersistentParameters) DeepCopy() *PersistentParameters {
	if in == nil {
		return nil
	}
	out := new(PersistentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingInitParameters) DeepCopyInto(out *SettingInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueList != nil {
		in, out := &in.ValueList, &out.ValueList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingInitParameters.
func (in *SettingInitParameters) DeepCopy() *SettingInitParameters {
	if in == nil {
		return nil
	}
	out := new(SettingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingObservation) DeepCopyInto(out *SettingObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueList != nil {
		in, out := &in.ValueList, &out.ValueList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingObservation.
func (in *SettingObservation) DeepCopy() *SettingObservation {
	if in == nil {
		return nil
	}
	out := new(SettingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingParameters) DeepCopyInto(out *SettingParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueList != nil {
		in, out := &in.ValueList, &out.ValueList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingParameters.
func (in *SettingParameters) DeepCopy() *SettingParameters {
	if in == nil {
		return nil
	}
	out := new(SettingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransientInitParameters) DeepCopyInto(out *TransientInitParameters) {
	*out = *in
	if in.Setting != nil {
		in, out := &in.Setting, &out.Setting
		*out = make([]TransientSettingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransientInitParameters.
func (in *TransientInitParameters) DeepCopy() *TransientInitParameters {
	if in == nil {
		return nil
	}
	out := new(TransientInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransientObservation) DeepCopyInto(out *TransientObservation) {
	*out = *in
	if in.Setting != nil {
		in, out := &in.Setting, &out.Setting
		*out = make([]TransientSettingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransientObservation.
func (in *TransientObservation) DeepCopy() *TransientObservation {
	if in == nil {
		return nil
	}
	out := new(TransientObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransientParameters) DeepCopyInto(out *TransientParameters) {
	*out = *in
	if in.Setting != nil {
		in, out := &in.Setting, &out.Setting
		*out = make([]TransientSettingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransientParameters.
func (in *TransientParameters) DeepCopy() *TransientParameters {
	if in == nil {
		return nil
	}
	out := new(TransientParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransientSettingInitParameters) DeepCopyInto(out *TransientSettingInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueList != nil {
		in, out := &in.ValueList, &out.ValueList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransientSettingInitParameters.
func (in *TransientSettingInitParameters) DeepCopy() *TransientSettingInitParameters {
	if in == nil {
		return nil
	}
	out := new(TransientSettingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransientSettingObservation) DeepCopyInto(out *TransientSettingObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueList != nil {
		in, out := &in.ValueList, &out.ValueList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransientSettingObservation.
func (in *TransientSettingObservation) DeepCopy() *TransientSettingObservation {
	if in == nil {
		return nil
	}
	out := new(TransientSettingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransientSettingParameters) DeepCopyInto(out *TransientSettingParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.ValueList != nil {
		in, out := &in.ValueList, &out.ValueList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransientSettingParameters.
func (in *TransientSettingParameters) DeepCopy() *TransientSettingParameters {
	if in == nil {
		return nil
	}
	out := new(TransientSettingParameters)
	in.DeepCopyInto(out)
	return out
}
