// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ElasticsearchUserElasticsearchConnectionInitParameters struct {

	// (String, Sensitive) API Key to use for authentication to Elasticsearch
	// API Key to use for authentication to Elasticsearch
	APIKeySecretRef *v1.LocalSecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Bearer Token to use for authentication to Elasticsearch
	// Bearer Token to use for authentication to Elasticsearch
	BearerTokenSecretRef *v1.LocalSecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	// encoded custom Certificate Authority certificate
	// PEM-encoded custom Certificate Authority certificate
	CAData *string `json:"caData,omitempty" tf:"ca_data,omitempty"`

	// (String) Path to a custom Certificate Authority certificate
	// Path to a custom Certificate Authority certificate
	CAFile *string `json:"caFile,omitempty" tf:"ca_file,omitempty"`

	// (String) PEM encoded certificate for client auth
	// PEM encoded certificate for client auth
	CertData *string `json:"certData,omitempty" tf:"cert_data,omitempty"`

	// (String) Path to a file containing the PEM encoded certificate for client auth
	// Path to a file containing the PEM encoded certificate for client auth
	CertFile *string `json:"certFile,omitempty" tf:"cert_file,omitempty"`

	Endpoints []*string `json:"endpointsSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) ES Client Authentication field to be used with the JWT token
	// ES Client Authentication field to be used with the JWT token
	EsClientAuthenticationSecretRef *v1.LocalSecretKeySelector `json:"esClientAuthenticationSecretRef,omitempty" tf:"-"`

	Headers map[string]*string `json:"headersSecretRef,omitempty" tf:"-"`

	// (Boolean) Disable TLS certificate validation
	// Disable TLS certificate validation
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String, Sensitive) PEM encoded private key for client auth
	// PEM encoded private key for client auth
	KeyDataSecretRef *v1.LocalSecretKeySelector `json:"keyDataSecretRef,omitempty" tf:"-"`

	// (String) Path to a file containing the PEM encoded private key for client auth
	// Path to a file containing the PEM encoded private key for client auth
	KeyFile *string `json:"keyFile,omitempty" tf:"key_file,omitempty"`

	// (String, Sensitive) The user's password. Passwords must be at least 6 characters long. Note: Consider using password_wo for better security with ephemeral resources.
	// Password to use for API authentication to Elasticsearch.
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) An identifier for the user (see the security API put user documentation for more details).
	// Username to use for API authentication to Elasticsearch.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ElasticsearchUserElasticsearchConnectionObservation struct {

	// encoded custom Certificate Authority certificate
	// PEM-encoded custom Certificate Authority certificate
	CAData *string `json:"caData,omitempty" tf:"ca_data,omitempty"`

	// (String) Path to a custom Certificate Authority certificate
	// Path to a custom Certificate Authority certificate
	CAFile *string `json:"caFile,omitempty" tf:"ca_file,omitempty"`

	// (String) PEM encoded certificate for client auth
	// PEM encoded certificate for client auth
	CertData *string `json:"certData,omitempty" tf:"cert_data,omitempty"`

	// (String) Path to a file containing the PEM encoded certificate for client auth
	// Path to a file containing the PEM encoded certificate for client auth
	CertFile *string `json:"certFile,omitempty" tf:"cert_file,omitempty"`

	// (Boolean) Disable TLS certificate validation
	// Disable TLS certificate validation
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String) Path to a file containing the PEM encoded private key for client auth
	// Path to a file containing the PEM encoded private key for client auth
	KeyFile *string `json:"keyFile,omitempty" tf:"key_file,omitempty"`

	// (String) An identifier for the user (see the security API put user documentation for more details).
	// Username to use for API authentication to Elasticsearch.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ElasticsearchUserElasticsearchConnectionParameters struct {

	// (String, Sensitive) API Key to use for authentication to Elasticsearch
	// API Key to use for authentication to Elasticsearch
	// +kubebuilder:validation:Optional
	APIKeySecretRef *v1.LocalSecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Bearer Token to use for authentication to Elasticsearch
	// Bearer Token to use for authentication to Elasticsearch
	// +kubebuilder:validation:Optional
	BearerTokenSecretRef *v1.LocalSecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	// encoded custom Certificate Authority certificate
	// PEM-encoded custom Certificate Authority certificate
	// +kubebuilder:validation:Optional
	CAData *string `json:"caData,omitempty" tf:"ca_data,omitempty"`

	// (String) Path to a custom Certificate Authority certificate
	// Path to a custom Certificate Authority certificate
	// +kubebuilder:validation:Optional
	CAFile *string `json:"caFile,omitempty" tf:"ca_file,omitempty"`

	// (String) PEM encoded certificate for client auth
	// PEM encoded certificate for client auth
	// +kubebuilder:validation:Optional
	CertData *string `json:"certData,omitempty" tf:"cert_data,omitempty"`

	// (String) Path to a file containing the PEM encoded certificate for client auth
	// Path to a file containing the PEM encoded certificate for client auth
	// +kubebuilder:validation:Optional
	CertFile *string `json:"certFile,omitempty" tf:"cert_file,omitempty"`

	// +kubebuilder:validation:Optional
	EndpointsSecretRef *[]v1.LocalSecretKeySelector `json:"endpointsSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) ES Client Authentication field to be used with the JWT token
	// ES Client Authentication field to be used with the JWT token
	// +kubebuilder:validation:Optional
	EsClientAuthenticationSecretRef *v1.LocalSecretKeySelector `json:"esClientAuthenticationSecretRef,omitempty" tf:"-"`

	// (Map of String, Sensitive) A list of headers to be sent with each request to Elasticsearch.
	// A list of headers to be sent with each request to Elasticsearch.
	// +kubebuilder:validation:Optional
	HeadersSecretRef *v1.LocalSecretReference `json:"headersSecretRef,omitempty" tf:"-"`

	// (Boolean) Disable TLS certificate validation
	// Disable TLS certificate validation
	// +kubebuilder:validation:Optional
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String, Sensitive) PEM encoded private key for client auth
	// PEM encoded private key for client auth
	// +kubebuilder:validation:Optional
	KeyDataSecretRef *v1.LocalSecretKeySelector `json:"keyDataSecretRef,omitempty" tf:"-"`

	// (String) Path to a file containing the PEM encoded private key for client auth
	// Path to a file containing the PEM encoded private key for client auth
	// +kubebuilder:validation:Optional
	KeyFile *string `json:"keyFile,omitempty" tf:"key_file,omitempty"`

	// (String, Sensitive) The user's password. Passwords must be at least 6 characters long. Note: Consider using password_wo for better security with ephemeral resources.
	// Password to use for API authentication to Elasticsearch.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) An identifier for the user (see the security API put user documentation for more details).
	// Username to use for API authentication to Elasticsearch.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ElasticsearchUserInitParameters struct {

	// (Block List, Deprecated) Elasticsearch connection configuration block. (see below for nested schema)
	// Elasticsearch connection configuration block.
	ElasticsearchConnection []ElasticsearchUserElasticsearchConnectionInitParameters `json:"elasticsearchConnection,omitempty" tf:"elasticsearch_connection,omitempty"`

	// (String) The email of the user.
	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) Specifies whether the user is enabled. The default value is true.
	// Specifies whether the user is enabled. The default value is true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The full name of the user.
	// The full name of the user.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) Arbitrary metadata that you want to associate with the user.
	// Arbitrary metadata that you want to associate with the user.
	Metadata *string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String, Sensitive) A hash of the user's password. This must be produced using the same hashing algorithm as has been configured for password storage (see the security settings documentation).
	// A hash of the user's password. This must be produced using the same hashing algorithm as has been configured for password storage (see the [security settings documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#hashing-settings)).
	PasswordHashSecretRef *v1.LocalSecretKeySelector `json:"passwordHashSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) The user's password. Passwords must be at least 6 characters long. Note: Consider using password_wo for better security with ephemeral resources.
	// The user's password. Passwords must be at least 6 characters long. Note: Consider using `password_wo` for better security with ephemeral resources.
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// only) Write-only password attribute for use with ephemeral resources. Passwords must be at least 6 characters long. Must be used with password_wo_version.
	// Write-only password attribute for use with ephemeral resources. Passwords must be at least 6 characters long. Must be used with `password_wo_version`.
	PasswordWoSecretRef *v1.LocalSecretKeySelector `json:"passwordWoSecretRef,omitempty" tf:"-"`

	// only password. This field is used to trigger updates when the password changes. Required when password_wo is set. Typically, you would use a hash of the password or a version identifier from your secret management system.
	// Version identifier for the write-only password. This field is used to trigger updates when the password changes. Required when `password_wo` is set. Typically, you would use a hash of the password or a version identifier from your secret management system.
	PasswordWoVersion *string `json:"passwordWoVersion,omitempty" tf:"password_wo_version,omitempty"`

	// (Set of String) A set of roles the user has. The roles determine the user's access permissions.
	// A set of roles the user has. The roles determine the user's access permissions.
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) An identifier for the user (see the security API put user documentation for more details).
	// An identifier for the user (see the [security API put user documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html#security-api-put-user-path-params) for more details).
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ElasticsearchUserObservation struct {

	// (Block List, Deprecated) Elasticsearch connection configuration block. (see below for nested schema)
	// Elasticsearch connection configuration block.
	ElasticsearchConnection []ElasticsearchUserElasticsearchConnectionObservation `json:"elasticsearchConnection,omitempty" tf:"elasticsearch_connection,omitempty"`

	// (String) The email of the user.
	// The email of the user.
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) Specifies whether the user is enabled. The default value is true.
	// Specifies whether the user is enabled. The default value is true.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The full name of the user.
	// The full name of the user.
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) Internal identifier of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Arbitrary metadata that you want to associate with the user.
	// Arbitrary metadata that you want to associate with the user.
	Metadata *string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// only password. This field is used to trigger updates when the password changes. Required when password_wo is set. Typically, you would use a hash of the password or a version identifier from your secret management system.
	// Version identifier for the write-only password. This field is used to trigger updates when the password changes. Required when `password_wo` is set. Typically, you would use a hash of the password or a version identifier from your secret management system.
	PasswordWoVersion *string `json:"passwordWoVersion,omitempty" tf:"password_wo_version,omitempty"`

	// (Set of String) A set of roles the user has. The roles determine the user's access permissions.
	// A set of roles the user has. The roles determine the user's access permissions.
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) An identifier for the user (see the security API put user documentation for more details).
	// An identifier for the user (see the [security API put user documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html#security-api-put-user-path-params) for more details).
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ElasticsearchUserParameters struct {

	// (Block List, Deprecated) Elasticsearch connection configuration block. (see below for nested schema)
	// Elasticsearch connection configuration block.
	// +kubebuilder:validation:Optional
	ElasticsearchConnection []ElasticsearchUserElasticsearchConnectionParameters `json:"elasticsearchConnection,omitempty" tf:"elasticsearch_connection,omitempty"`

	// (String) The email of the user.
	// The email of the user.
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// (Boolean) Specifies whether the user is enabled. The default value is true.
	// Specifies whether the user is enabled. The default value is true.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The full name of the user.
	// The full name of the user.
	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// (String) Arbitrary metadata that you want to associate with the user.
	// Arbitrary metadata that you want to associate with the user.
	// +kubebuilder:validation:Optional
	Metadata *string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (String, Sensitive) A hash of the user's password. This must be produced using the same hashing algorithm as has been configured for password storage (see the security settings documentation).
	// A hash of the user's password. This must be produced using the same hashing algorithm as has been configured for password storage (see the [security settings documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#hashing-settings)).
	// +kubebuilder:validation:Optional
	PasswordHashSecretRef *v1.LocalSecretKeySelector `json:"passwordHashSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) The user's password. Passwords must be at least 6 characters long. Note: Consider using password_wo for better security with ephemeral resources.
	// The user's password. Passwords must be at least 6 characters long. Note: Consider using `password_wo` for better security with ephemeral resources.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// only) Write-only password attribute for use with ephemeral resources. Passwords must be at least 6 characters long. Must be used with password_wo_version.
	// Write-only password attribute for use with ephemeral resources. Passwords must be at least 6 characters long. Must be used with `password_wo_version`.
	// +kubebuilder:validation:Optional
	PasswordWoSecretRef *v1.LocalSecretKeySelector `json:"passwordWoSecretRef,omitempty" tf:"-"`

	// only password. This field is used to trigger updates when the password changes. Required when password_wo is set. Typically, you would use a hash of the password or a version identifier from your secret management system.
	// Version identifier for the write-only password. This field is used to trigger updates when the password changes. Required when `password_wo` is set. Typically, you would use a hash of the password or a version identifier from your secret management system.
	// +kubebuilder:validation:Optional
	PasswordWoVersion *string `json:"passwordWoVersion,omitempty" tf:"password_wo_version,omitempty"`

	// (Set of String) A set of roles the user has. The roles determine the user's access permissions.
	// A set of roles the user has. The roles determine the user's access permissions.
	// +kubebuilder:validation:Optional
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// (String) An identifier for the user (see the security API put user documentation for more details).
	// An identifier for the user (see the [security API put user documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html#security-api-put-user-path-params) for more details).
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

// ElasticsearchUserSpec defines the desired state of ElasticsearchUser
type ElasticsearchUserSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ElasticsearchUserParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ElasticsearchUserInitParameters `json:"initProvider,omitempty"`
}

// ElasticsearchUserStatus defines the observed state of ElasticsearchUser.
type ElasticsearchUserStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ElasticsearchUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ElasticsearchUser is the Schema for the ElasticsearchUsers API. Adds and updates users in the native realm. These users are commonly referred to as native users. See the Elasticsearch security user API documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html for more details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,elasticstack}
type ElasticsearchUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roles) || (has(self.initProvider) && has(self.initProvider.roles))",message="spec.forProvider.roles is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.username) || (has(self.initProvider) && has(self.initProvider.username))",message="spec.forProvider.username is a required parameter"
	Spec   ElasticsearchUserSpec   `json:"spec"`
	Status ElasticsearchUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ElasticsearchUserList contains a list of ElasticsearchUsers
type ElasticsearchUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ElasticsearchUser `json:"items"`
}

// Repository type metadata.
var (
	ElasticsearchUser_Kind             = "ElasticsearchUser"
	ElasticsearchUser_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ElasticsearchUser_Kind}.String()
	ElasticsearchUser_KindAPIVersion   = ElasticsearchUser_Kind + "." + CRDGroupVersion.String()
	ElasticsearchUser_GroupVersionKind = CRDGroupVersion.WithKind(ElasticsearchUser_Kind)
)

func init() {
	SchemeBuilder.Register(&ElasticsearchUser{}, &ElasticsearchUserList{})
}
