// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ApplicationsInitParameters struct {

	// (String) The name of the application to which this entry applies.
	// The name of the application to which this entry applies.
	Application *string `json:"application,omitempty" tf:"application,omitempty"`

	// (Set of String) A list of strings, where each element is the name of an application privilege or action.
	// A list of strings, where each element is the name of an application privilege or action.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (Set of String) A list resources to which the privileges are applied.
	// A list resources to which the privileges are applied.
	// +listType=set
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ApplicationsObservation struct {

	// (String) The name of the application to which this entry applies.
	// The name of the application to which this entry applies.
	Application *string `json:"application,omitempty" tf:"application,omitempty"`

	// (Set of String) A list of strings, where each element is the name of an application privilege or action.
	// A list of strings, where each element is the name of an application privilege or action.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (Set of String) A list resources to which the privileges are applied.
	// A list resources to which the privileges are applied.
	// +listType=set
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type ApplicationsParameters struct {

	// (String) The name of the application to which this entry applies.
	// The name of the application to which this entry applies.
	// +kubebuilder:validation:Optional
	Application *string `json:"application" tf:"application,omitempty"`

	// (Set of String) A list of strings, where each element is the name of an application privilege or action.
	// A list of strings, where each element is the name of an application privilege or action.
	// +kubebuilder:validation:Optional
	// +listType=set
	Privileges []*string `json:"privileges" tf:"privileges,omitempty"`

	// (Set of String) A list resources to which the privileges are applied.
	// A list resources to which the privileges are applied.
	// +kubebuilder:validation:Optional
	// +listType=set
	Resources []*string `json:"resources" tf:"resources,omitempty"`
}

type ElasticsearchConnectionInitParameters struct {

	// (String, Sensitive) API Key to use for authentication to Elasticsearch
	// API Key to use for authentication to Elasticsearch
	APIKeySecretRef *v1.LocalSecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Bearer Token to use for authentication to Elasticsearch
	// Bearer Token to use for authentication to Elasticsearch
	BearerTokenSecretRef *v1.LocalSecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	// encoded custom Certificate Authority certificate
	// PEM-encoded custom Certificate Authority certificate
	CAData *string `json:"caData,omitempty" tf:"ca_data,omitempty"`

	// (String) Path to a custom Certificate Authority certificate
	// Path to a custom Certificate Authority certificate
	CAFile *string `json:"caFile,omitempty" tf:"ca_file,omitempty"`

	// (String) PEM encoded certificate for client auth
	// PEM encoded certificate for client auth
	CertData *string `json:"certData,omitempty" tf:"cert_data,omitempty"`

	// (String) Path to a file containing the PEM encoded certificate for client auth
	// Path to a file containing the PEM encoded certificate for client auth
	CertFile *string `json:"certFile,omitempty" tf:"cert_file,omitempty"`

	Endpoints []*string `json:"endpointsSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) ES Client Authentication field to be used with the JWT token
	// ES Client Authentication field to be used with the JWT token
	EsClientAuthenticationSecretRef *v1.LocalSecretKeySelector `json:"esClientAuthenticationSecretRef,omitempty" tf:"-"`

	Headers map[string]*string `json:"headersSecretRef,omitempty" tf:"-"`

	// (Boolean) Disable TLS certificate validation
	// Disable TLS certificate validation
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String, Sensitive) PEM encoded private key for client auth
	// PEM encoded private key for client auth
	KeyDataSecretRef *v1.LocalSecretKeySelector `json:"keyDataSecretRef,omitempty" tf:"-"`

	// (String) Path to a file containing the PEM encoded private key for client auth
	// Path to a file containing the PEM encoded private key for client auth
	KeyFile *string `json:"keyFile,omitempty" tf:"key_file,omitempty"`

	// (String, Sensitive) Password to use for API authentication to Elasticsearch.
	// Password to use for API authentication to Elasticsearch.
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) Username to use for API authentication to Elasticsearch.
	// Username to use for API authentication to Elasticsearch.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ElasticsearchConnectionObservation struct {

	// encoded custom Certificate Authority certificate
	// PEM-encoded custom Certificate Authority certificate
	CAData *string `json:"caData,omitempty" tf:"ca_data,omitempty"`

	// (String) Path to a custom Certificate Authority certificate
	// Path to a custom Certificate Authority certificate
	CAFile *string `json:"caFile,omitempty" tf:"ca_file,omitempty"`

	// (String) PEM encoded certificate for client auth
	// PEM encoded certificate for client auth
	CertData *string `json:"certData,omitempty" tf:"cert_data,omitempty"`

	// (String) Path to a file containing the PEM encoded certificate for client auth
	// Path to a file containing the PEM encoded certificate for client auth
	CertFile *string `json:"certFile,omitempty" tf:"cert_file,omitempty"`

	// (Boolean) Disable TLS certificate validation
	// Disable TLS certificate validation
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String) Path to a file containing the PEM encoded private key for client auth
	// Path to a file containing the PEM encoded private key for client auth
	KeyFile *string `json:"keyFile,omitempty" tf:"key_file,omitempty"`

	// (String) Username to use for API authentication to Elasticsearch.
	// Username to use for API authentication to Elasticsearch.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ElasticsearchConnectionParameters struct {

	// (String, Sensitive) API Key to use for authentication to Elasticsearch
	// API Key to use for authentication to Elasticsearch
	// +kubebuilder:validation:Optional
	APIKeySecretRef *v1.LocalSecretKeySelector `json:"apiKeySecretRef,omitempty" tf:"-"`

	// (String, Sensitive) Bearer Token to use for authentication to Elasticsearch
	// Bearer Token to use for authentication to Elasticsearch
	// +kubebuilder:validation:Optional
	BearerTokenSecretRef *v1.LocalSecretKeySelector `json:"bearerTokenSecretRef,omitempty" tf:"-"`

	// encoded custom Certificate Authority certificate
	// PEM-encoded custom Certificate Authority certificate
	// +kubebuilder:validation:Optional
	CAData *string `json:"caData,omitempty" tf:"ca_data,omitempty"`

	// (String) Path to a custom Certificate Authority certificate
	// Path to a custom Certificate Authority certificate
	// +kubebuilder:validation:Optional
	CAFile *string `json:"caFile,omitempty" tf:"ca_file,omitempty"`

	// (String) PEM encoded certificate for client auth
	// PEM encoded certificate for client auth
	// +kubebuilder:validation:Optional
	CertData *string `json:"certData,omitempty" tf:"cert_data,omitempty"`

	// (String) Path to a file containing the PEM encoded certificate for client auth
	// Path to a file containing the PEM encoded certificate for client auth
	// +kubebuilder:validation:Optional
	CertFile *string `json:"certFile,omitempty" tf:"cert_file,omitempty"`

	// +kubebuilder:validation:Optional
	EndpointsSecretRef *[]v1.LocalSecretKeySelector `json:"endpointsSecretRef,omitempty" tf:"-"`

	// (String, Sensitive) ES Client Authentication field to be used with the JWT token
	// ES Client Authentication field to be used with the JWT token
	// +kubebuilder:validation:Optional
	EsClientAuthenticationSecretRef *v1.LocalSecretKeySelector `json:"esClientAuthenticationSecretRef,omitempty" tf:"-"`

	// (Map of String, Sensitive) A list of headers to be sent with each request to Elasticsearch.
	// A list of headers to be sent with each request to Elasticsearch.
	// +kubebuilder:validation:Optional
	HeadersSecretRef *v1.LocalSecretReference `json:"headersSecretRef,omitempty" tf:"-"`

	// (Boolean) Disable TLS certificate validation
	// Disable TLS certificate validation
	// +kubebuilder:validation:Optional
	Insecure *bool `json:"insecure,omitempty" tf:"insecure,omitempty"`

	// (String, Sensitive) PEM encoded private key for client auth
	// PEM encoded private key for client auth
	// +kubebuilder:validation:Optional
	KeyDataSecretRef *v1.LocalSecretKeySelector `json:"keyDataSecretRef,omitempty" tf:"-"`

	// (String) Path to a file containing the PEM encoded private key for client auth
	// Path to a file containing the PEM encoded private key for client auth
	// +kubebuilder:validation:Optional
	KeyFile *string `json:"keyFile,omitempty" tf:"key_file,omitempty"`

	// (String, Sensitive) Password to use for API authentication to Elasticsearch.
	// Password to use for API authentication to Elasticsearch.
	// +kubebuilder:validation:Optional
	PasswordSecretRef *v1.LocalSecretKeySelector `json:"passwordSecretRef,omitempty" tf:"-"`

	// (String) Username to use for API authentication to Elasticsearch.
	// Username to use for API authentication to Elasticsearch.
	// +kubebuilder:validation:Optional
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type ElasticsearchRoleInitParameters struct {

	// (Block Set) A list of application privilege entries. (see below for nested schema)
	// A list of application privilege entries.
	Applications []ApplicationsInitParameters `json:"applications,omitempty" tf:"applications,omitempty"`

	// (Set of String) A list of cluster privileges. These privileges define the cluster level actions that users with this role are able to execute.
	// A list of cluster privileges. These privileges define the cluster level actions that users with this role are able to execute.
	// +listType=set
	Cluster []*string `json:"cluster,omitempty" tf:"cluster,omitempty"`

	// (String) The description of the role.
	// The description of the role.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Deprecated) Elasticsearch connection configuration block. (see below for nested schema)
	// Elasticsearch connection configuration block.
	ElasticsearchConnection []ElasticsearchConnectionInitParameters `json:"elasticsearchConnection,omitempty" tf:"elasticsearch_connection,omitempty"`

	// (String) An object defining global privileges.
	// An object defining global privileges.
	Global *string `json:"global,omitempty" tf:"global,omitempty"`

	// (Block Set) A list of indices permissions entries. (see below for nested schema)
	// A list of indices permissions entries.
	Indices []IndicesInitParameters `json:"indices,omitempty" tf:"indices,omitempty"`

	// data.
	// Optional meta-data.
	Metadata *string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Block Set) A list of remote indices permissions entries. Remote indices are effective for remote clusters configured with the API key based model. They have no effect for remote clusters configured with the certificate based model. (see below for nested schema)
	// A list of remote indices permissions entries. Remote indices are effective for remote clusters configured with the API key based model. They have no effect for remote clusters configured with the certificate based model.
	RemoteIndices []RemoteIndicesInitParameters `json:"remoteIndices,omitempty" tf:"remote_indices,omitempty"`

	// (Set of String) A list of users that the owners of this role can impersonate.
	// A list of users that the owners of this role can impersonate.
	// +listType=set
	RunAs []*string `json:"runAs,omitempty" tf:"run_as,omitempty"`
}

type ElasticsearchRoleObservation struct {

	// (Block Set) A list of application privilege entries. (see below for nested schema)
	// A list of application privilege entries.
	Applications []ApplicationsObservation `json:"applications,omitempty" tf:"applications,omitempty"`

	// (Set of String) A list of cluster privileges. These privileges define the cluster level actions that users with this role are able to execute.
	// A list of cluster privileges. These privileges define the cluster level actions that users with this role are able to execute.
	// +listType=set
	Cluster []*string `json:"cluster,omitempty" tf:"cluster,omitempty"`

	// (String) The description of the role.
	// The description of the role.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Deprecated) Elasticsearch connection configuration block. (see below for nested schema)
	// Elasticsearch connection configuration block.
	ElasticsearchConnection []ElasticsearchConnectionObservation `json:"elasticsearchConnection,omitempty" tf:"elasticsearch_connection,omitempty"`

	// (String) An object defining global privileges.
	// An object defining global privileges.
	Global *string `json:"global,omitempty" tf:"global,omitempty"`

	// (String) Internal identifier of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Block Set) A list of indices permissions entries. (see below for nested schema)
	// A list of indices permissions entries.
	Indices []IndicesObservation `json:"indices,omitempty" tf:"indices,omitempty"`

	// data.
	// Optional meta-data.
	Metadata *string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Block Set) A list of remote indices permissions entries. Remote indices are effective for remote clusters configured with the API key based model. They have no effect for remote clusters configured with the certificate based model. (see below for nested schema)
	// A list of remote indices permissions entries. Remote indices are effective for remote clusters configured with the API key based model. They have no effect for remote clusters configured with the certificate based model.
	RemoteIndices []RemoteIndicesObservation `json:"remoteIndices,omitempty" tf:"remote_indices,omitempty"`

	// (Set of String) A list of users that the owners of this role can impersonate.
	// A list of users that the owners of this role can impersonate.
	// +listType=set
	RunAs []*string `json:"runAs,omitempty" tf:"run_as,omitempty"`
}

type ElasticsearchRoleParameters struct {

	// (Block Set) A list of application privilege entries. (see below for nested schema)
	// A list of application privilege entries.
	// +kubebuilder:validation:Optional
	Applications []ApplicationsParameters `json:"applications,omitempty" tf:"applications,omitempty"`

	// (Set of String) A list of cluster privileges. These privileges define the cluster level actions that users with this role are able to execute.
	// A list of cluster privileges. These privileges define the cluster level actions that users with this role are able to execute.
	// +kubebuilder:validation:Optional
	// +listType=set
	Cluster []*string `json:"cluster,omitempty" tf:"cluster,omitempty"`

	// (String) The description of the role.
	// The description of the role.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Block List, Deprecated) Elasticsearch connection configuration block. (see below for nested schema)
	// Elasticsearch connection configuration block.
	// +kubebuilder:validation:Optional
	ElasticsearchConnection []ElasticsearchConnectionParameters `json:"elasticsearchConnection,omitempty" tf:"elasticsearch_connection,omitempty"`

	// (String) An object defining global privileges.
	// An object defining global privileges.
	// +kubebuilder:validation:Optional
	Global *string `json:"global,omitempty" tf:"global,omitempty"`

	// (Block Set) A list of indices permissions entries. (see below for nested schema)
	// A list of indices permissions entries.
	// +kubebuilder:validation:Optional
	Indices []IndicesParameters `json:"indices,omitempty" tf:"indices,omitempty"`

	// data.
	// Optional meta-data.
	// +kubebuilder:validation:Optional
	Metadata *string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// (Block Set) A list of remote indices permissions entries. Remote indices are effective for remote clusters configured with the API key based model. They have no effect for remote clusters configured with the certificate based model. (see below for nested schema)
	// A list of remote indices permissions entries. Remote indices are effective for remote clusters configured with the API key based model. They have no effect for remote clusters configured with the certificate based model.
	// +kubebuilder:validation:Optional
	RemoteIndices []RemoteIndicesParameters `json:"remoteIndices,omitempty" tf:"remote_indices,omitempty"`

	// (Set of String) A list of users that the owners of this role can impersonate.
	// A list of users that the owners of this role can impersonate.
	// +kubebuilder:validation:Optional
	// +listType=set
	RunAs []*string `json:"runAs,omitempty" tf:"run_as,omitempty"`
}

type FieldSecurityInitParameters struct {

	// (Set of String) List of the fields to which the grants will not be applied.
	// List of the fields to which the grants will not be applied.
	// +listType=set
	Except []*string `json:"except,omitempty" tf:"except,omitempty"`

	// (Set of String) List of the fields to grant the access to.
	// List of the fields to grant the access to.
	// +listType=set
	Grant []*string `json:"grant,omitempty" tf:"grant,omitempty"`
}

type FieldSecurityObservation struct {

	// (Set of String) List of the fields to which the grants will not be applied.
	// List of the fields to which the grants will not be applied.
	// +listType=set
	Except []*string `json:"except,omitempty" tf:"except,omitempty"`

	// (Set of String) List of the fields to grant the access to.
	// List of the fields to grant the access to.
	// +listType=set
	Grant []*string `json:"grant,omitempty" tf:"grant,omitempty"`
}

type FieldSecurityParameters struct {

	// (Set of String) List of the fields to which the grants will not be applied.
	// List of the fields to which the grants will not be applied.
	// +kubebuilder:validation:Optional
	// +listType=set
	Except []*string `json:"except,omitempty" tf:"except,omitempty"`

	// (Set of String) List of the fields to grant the access to.
	// List of the fields to grant the access to.
	// +kubebuilder:validation:Optional
	// +listType=set
	Grant []*string `json:"grant,omitempty" tf:"grant,omitempty"`
}

type IndicesInitParameters struct {

	// (Boolean) Include matching restricted indices in names parameter. Usage is strongly discouraged as it can grant unrestricted operations on critical data, make the entire system unstable or leak sensitive information.
	// Include matching restricted indices in names parameter. Usage is strongly discouraged as it can grant unrestricted operations on critical data, make the entire system unstable or leak sensitive information.
	AllowRestrictedIndices *bool `json:"allowRestrictedIndices,omitempty" tf:"allow_restricted_indices,omitempty"`

	// (Block, Optional) The document fields that the owners of the role have read access to. (see below for nested schema)
	// The document fields that the owners of the role have read access to.
	FieldSecurity []FieldSecurityInitParameters `json:"fieldSecurity,omitempty" tf:"field_security,omitempty"`

	// (Set of String) A list of indices (or index name patterns) to which the permissions in this entry apply.
	// A list of indices (or index name patterns) to which the permissions in this entry apply.
	// +listType=set
	Names []*string `json:"names,omitempty" tf:"names,omitempty"`

	// (Set of String) A list of strings, where each element is the name of an application privilege or action.
	// The index level privileges that the owners of the role have on the specified indices.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (String) A search query that defines the documents the owners of the role have read access to.
	// A search query that defines the documents the owners of the role have read access to.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

type IndicesObservation struct {

	// (Boolean) Include matching restricted indices in names parameter. Usage is strongly discouraged as it can grant unrestricted operations on critical data, make the entire system unstable or leak sensitive information.
	// Include matching restricted indices in names parameter. Usage is strongly discouraged as it can grant unrestricted operations on critical data, make the entire system unstable or leak sensitive information.
	AllowRestrictedIndices *bool `json:"allowRestrictedIndices,omitempty" tf:"allow_restricted_indices,omitempty"`

	// (Block, Optional) The document fields that the owners of the role have read access to. (see below for nested schema)
	// The document fields that the owners of the role have read access to.
	FieldSecurity []FieldSecurityObservation `json:"fieldSecurity,omitempty" tf:"field_security,omitempty"`

	// (Set of String) A list of indices (or index name patterns) to which the permissions in this entry apply.
	// A list of indices (or index name patterns) to which the permissions in this entry apply.
	// +listType=set
	Names []*string `json:"names,omitempty" tf:"names,omitempty"`

	// (Set of String) A list of strings, where each element is the name of an application privilege or action.
	// The index level privileges that the owners of the role have on the specified indices.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (String) A search query that defines the documents the owners of the role have read access to.
	// A search query that defines the documents the owners of the role have read access to.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

type IndicesParameters struct {

	// (Boolean) Include matching restricted indices in names parameter. Usage is strongly discouraged as it can grant unrestricted operations on critical data, make the entire system unstable or leak sensitive information.
	// Include matching restricted indices in names parameter. Usage is strongly discouraged as it can grant unrestricted operations on critical data, make the entire system unstable or leak sensitive information.
	// +kubebuilder:validation:Optional
	AllowRestrictedIndices *bool `json:"allowRestrictedIndices,omitempty" tf:"allow_restricted_indices,omitempty"`

	// (Block, Optional) The document fields that the owners of the role have read access to. (see below for nested schema)
	// The document fields that the owners of the role have read access to.
	// +kubebuilder:validation:Optional
	FieldSecurity []FieldSecurityParameters `json:"fieldSecurity,omitempty" tf:"field_security,omitempty"`

	// (Set of String) A list of indices (or index name patterns) to which the permissions in this entry apply.
	// A list of indices (or index name patterns) to which the permissions in this entry apply.
	// +kubebuilder:validation:Optional
	// +listType=set
	Names []*string `json:"names" tf:"names,omitempty"`

	// (Set of String) A list of strings, where each element is the name of an application privilege or action.
	// The index level privileges that the owners of the role have on the specified indices.
	// +kubebuilder:validation:Optional
	// +listType=set
	Privileges []*string `json:"privileges" tf:"privileges,omitempty"`

	// (String) A search query that defines the documents the owners of the role have read access to.
	// A search query that defines the documents the owners of the role have read access to.
	// +kubebuilder:validation:Optional
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

type RemoteIndicesFieldSecurityInitParameters struct {

	// (Set of String) List of the fields to which the grants will not be applied.
	// List of the fields to which the grants will not be applied.
	// +listType=set
	Except []*string `json:"except,omitempty" tf:"except,omitempty"`

	// (Set of String) List of the fields to grant the access to.
	// List of the fields to grant the access to.
	// +listType=set
	Grant []*string `json:"grant,omitempty" tf:"grant,omitempty"`
}

type RemoteIndicesFieldSecurityObservation struct {

	// (Set of String) List of the fields to which the grants will not be applied.
	// List of the fields to which the grants will not be applied.
	// +listType=set
	Except []*string `json:"except,omitempty" tf:"except,omitempty"`

	// (Set of String) List of the fields to grant the access to.
	// List of the fields to grant the access to.
	// +listType=set
	Grant []*string `json:"grant,omitempty" tf:"grant,omitempty"`
}

type RemoteIndicesFieldSecurityParameters struct {

	// (Set of String) List of the fields to which the grants will not be applied.
	// List of the fields to which the grants will not be applied.
	// +kubebuilder:validation:Optional
	// +listType=set
	Except []*string `json:"except,omitempty" tf:"except,omitempty"`

	// (Set of String) List of the fields to grant the access to.
	// List of the fields to grant the access to.
	// +kubebuilder:validation:Optional
	// +listType=set
	Grant []*string `json:"grant,omitempty" tf:"grant,omitempty"`
}

type RemoteIndicesInitParameters struct {

	// (Set of String) A list of cluster aliases to which the permissions in this entry apply.
	// A list of cluster aliases to which the permissions in this entry apply.
	// +listType=set
	Clusters []*string `json:"clusters,omitempty" tf:"clusters,omitempty"`

	// (Block, Optional) The document fields that the owners of the role have read access to. (see below for nested schema)
	// The document fields that the owners of the role have read access to.
	FieldSecurity []RemoteIndicesFieldSecurityInitParameters `json:"fieldSecurity,omitempty" tf:"field_security,omitempty"`

	// (Set of String) A list of indices (or index name patterns) to which the permissions in this entry apply.
	// A list of indices (or index name patterns) to which the permissions in this entry apply.
	// +listType=set
	Names []*string `json:"names,omitempty" tf:"names,omitempty"`

	// (Set of String) A list of strings, where each element is the name of an application privilege or action.
	// The index level privileges that the owners of the role have on the specified indices.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (String) A search query that defines the documents the owners of the role have read access to.
	// A search query that defines the documents the owners of the role have read access to.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

type RemoteIndicesObservation struct {

	// (Set of String) A list of cluster aliases to which the permissions in this entry apply.
	// A list of cluster aliases to which the permissions in this entry apply.
	// +listType=set
	Clusters []*string `json:"clusters,omitempty" tf:"clusters,omitempty"`

	// (Block, Optional) The document fields that the owners of the role have read access to. (see below for nested schema)
	// The document fields that the owners of the role have read access to.
	FieldSecurity []RemoteIndicesFieldSecurityObservation `json:"fieldSecurity,omitempty" tf:"field_security,omitempty"`

	// (Set of String) A list of indices (or index name patterns) to which the permissions in this entry apply.
	// A list of indices (or index name patterns) to which the permissions in this entry apply.
	// +listType=set
	Names []*string `json:"names,omitempty" tf:"names,omitempty"`

	// (Set of String) A list of strings, where each element is the name of an application privilege or action.
	// The index level privileges that the owners of the role have on the specified indices.
	// +listType=set
	Privileges []*string `json:"privileges,omitempty" tf:"privileges,omitempty"`

	// (String) A search query that defines the documents the owners of the role have read access to.
	// A search query that defines the documents the owners of the role have read access to.
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

type RemoteIndicesParameters struct {

	// (Set of String) A list of cluster aliases to which the permissions in this entry apply.
	// A list of cluster aliases to which the permissions in this entry apply.
	// +kubebuilder:validation:Optional
	// +listType=set
	Clusters []*string `json:"clusters" tf:"clusters,omitempty"`

	// (Block, Optional) The document fields that the owners of the role have read access to. (see below for nested schema)
	// The document fields that the owners of the role have read access to.
	// +kubebuilder:validation:Optional
	FieldSecurity []RemoteIndicesFieldSecurityParameters `json:"fieldSecurity,omitempty" tf:"field_security,omitempty"`

	// (Set of String) A list of indices (or index name patterns) to which the permissions in this entry apply.
	// A list of indices (or index name patterns) to which the permissions in this entry apply.
	// +kubebuilder:validation:Optional
	// +listType=set
	Names []*string `json:"names" tf:"names,omitempty"`

	// (Set of String) A list of strings, where each element is the name of an application privilege or action.
	// The index level privileges that the owners of the role have on the specified indices.
	// +kubebuilder:validation:Optional
	// +listType=set
	Privileges []*string `json:"privileges" tf:"privileges,omitempty"`

	// (String) A search query that defines the documents the owners of the role have read access to.
	// A search query that defines the documents the owners of the role have read access to.
	// +kubebuilder:validation:Optional
	Query *string `json:"query,omitempty" tf:"query,omitempty"`
}

// ElasticsearchRoleSpec defines the desired state of ElasticsearchRole
type ElasticsearchRoleSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ElasticsearchRoleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ElasticsearchRoleInitParameters `json:"initProvider,omitempty"`
}

// ElasticsearchRoleStatus defines the observed state of ElasticsearchRole.
type ElasticsearchRoleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ElasticsearchRoleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ElasticsearchRole is the Schema for the ElasticsearchRoles API. Adds and updates roles in the native realm. See the role API documentation https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role.html for more details.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,elasticstack}
type ElasticsearchRole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ElasticsearchRoleSpec   `json:"spec"`
	Status            ElasticsearchRoleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ElasticsearchRoleList contains a list of ElasticsearchRoles
type ElasticsearchRoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ElasticsearchRole `json:"items"`
}

// Repository type metadata.
var (
	ElasticsearchRole_Kind             = "ElasticsearchRole"
	ElasticsearchRole_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ElasticsearchRole_Kind}.String()
	ElasticsearchRole_KindAPIVersion   = ElasticsearchRole_Kind + "." + CRDGroupVersion.String()
	ElasticsearchRole_GroupVersionKind = CRDGroupVersion.WithKind(ElasticsearchRole_Kind)
)

func init() {
	SchemeBuilder.Register(&ElasticsearchRole{}, &ElasticsearchRoleList{})
}
