// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"dario.cat/mergo"
	"github.com/pkg/errors"

	"github.com/crossplane/upjet/v2/pkg/resource"
	"github.com/crossplane/upjet/v2/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this ElasticsearchUser
func (mg *ElasticsearchUser) GetTerraformResourceType() string {
	return "elasticstack_elasticsearch_security_user"
}

// GetConnectionDetailsMapping for this ElasticsearchUser
func (tr *ElasticsearchUser) GetConnectionDetailsMapping() map[string]string {
	return map[string]string{"elasticsearch_connection[*].api_key": "elasticsearchConnection[*].apiKeySecretRef", "elasticsearch_connection[*].bearer_token": "elasticsearchConnection[*].bearerTokenSecretRef", "elasticsearch_connection[*].endpoints[*]": "elasticsearchConnection[*].endpointsSecretRef[*]", "elasticsearch_connection[*].es_client_authentication": "elasticsearchConnection[*].esClientAuthenticationSecretRef", "elasticsearch_connection[*].headers": "elasticsearchConnection[*].headersSecretRef", "elasticsearch_connection[*].key_data": "elasticsearchConnection[*].keyDataSecretRef", "elasticsearch_connection[*].password": "elasticsearchConnection[*].passwordSecretRef", "password": "passwordSecretRef", "password_hash": "passwordHashSecretRef", "password_wo": "passwordWoSecretRef"}
}

// GetObservation of this ElasticsearchUser
func (tr *ElasticsearchUser) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this ElasticsearchUser
func (tr *ElasticsearchUser) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this ElasticsearchUser
func (tr *ElasticsearchUser) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this ElasticsearchUser
func (tr *ElasticsearchUser) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this ElasticsearchUser
func (tr *ElasticsearchUser) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// GetInitParameters of this ElasticsearchUser
func (tr *ElasticsearchUser) GetInitParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.InitProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// GetInitParameters of this ElasticsearchUser
func (tr *ElasticsearchUser) GetMergedParameters(shouldMergeInitProvider bool) (map[string]any, error) {
	params, err := tr.GetParameters()
	if err != nil {
		return nil, errors.Wrapf(err, "cannot get parameters for resource \"%s/%s\"", tr.GetNamespace(), tr.GetName())
	}
	if !shouldMergeInitProvider {
		return params, nil
	}

	initParams, err := tr.GetInitParameters()
	if err != nil {
		return nil, errors.Wrapf(err, "cannot get init parameters for resource \"%s/%s\"", tr.GetNamespace(), tr.GetName())
	}

	// Note(lsviben): mergo.WithSliceDeepCopy is needed to merge the
	// slices from the initProvider to forProvider. As it also sets
	// overwrite to true, we need to set it back to false, we don't
	// want to overwrite the forProvider fields with the initProvider
	// fields.
	err = mergo.Merge(&params, initParams, mergo.WithSliceDeepCopy, func(c *mergo.Config) {
		c.Overwrite = false
	})
	if err != nil {
		return nil, errors.Wrapf(err, "cannot merge spec.initProvider and spec.forProvider parameters for resource \"%s/%s\"", tr.GetNamespace(), tr.GetName())
	}

	return params, nil
}

// LateInitialize this ElasticsearchUser using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *ElasticsearchUser) LateInitialize(attrs []byte) (bool, error) {
	params := &ElasticsearchUserParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *ElasticsearchUser) GetTerraformSchemaVersion() int {
	return 0
}
