//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureInitParameters) DeepCopyInto(out *AzureInitParameters) {
	*out = *in
	if in.BasePath != nil {
		in, out := &in.BasePath, &out.BasePath
		*out = new(string)
		**out = **in
	}
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	if in.LocationMode != nil {
		in, out := &in.LocationMode, &out.LocationMode
		*out = new(string)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureInitParameters.
func (in *AzureInitParameters) DeepCopy() *AzureInitParameters {
	if in == nil {
		return nil
	}
	out := new(AzureInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureObservation) DeepCopyInto(out *AzureObservation) {
	*out = *in
	if in.BasePath != nil {
		in, out := &in.BasePath, &out.BasePath
		*out = new(string)
		**out = **in
	}
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	if in.LocationMode != nil {
		in, out := &in.LocationMode, &out.LocationMode
		*out = new(string)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureObservation.
func (in *AzureObservation) DeepCopy() *AzureObservation {
	if in == nil {
		return nil
	}
	out := new(AzureObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureParameters) DeepCopyInto(out *AzureParameters) {
	*out = *in
	if in.BasePath != nil {
		in, out := &in.BasePath, &out.BasePath
		*out = new(string)
		**out = **in
	}
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(string)
		**out = **in
	}
	if in.LocationMode != nil {
		in, out := &in.LocationMode, &out.LocationMode
		*out = new(string)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureParameters.
func (in *AzureParameters) DeepCopy() *AzureParameters {
	if in == nil {
		return nil
	}
	out := new(AzureParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConnectionInitParameters) DeepCopyInto(out *ElasticsearchConnectionInitParameters) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EsClientAuthenticationSecretRef != nil {
		in, out := &in.EsClientAuthenticationSecretRef, &out.EsClientAuthenticationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyDataSecretRef != nil {
		in, out := &in.KeyDataSecretRef, &out.KeyDataSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConnectionInitParameters.
func (in *ElasticsearchConnectionInitParameters) DeepCopy() *ElasticsearchConnectionInitParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConnectionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConnectionObservation) DeepCopyInto(out *ElasticsearchConnectionObservation) {
	*out = *in
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConnectionObservation.
func (in *ElasticsearchConnectionObservation) DeepCopy() *ElasticsearchConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConnectionParameters) DeepCopyInto(out *ElasticsearchConnectionParameters) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.EndpointsSecretRef != nil {
		in, out := &in.EndpointsSecretRef, &out.EndpointsSecretRef
		*out = new([]v1.SecretKeySelector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.SecretKeySelector, len(*in))
			copy(*out, *in)
		}
	}
	if in.EsClientAuthenticationSecretRef != nil {
		in, out := &in.EsClientAuthenticationSecretRef, &out.EsClientAuthenticationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.HeadersSecretRef != nil {
		in, out := &in.HeadersSecretRef, &out.HeadersSecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyDataSecretRef != nil {
		in, out := &in.KeyDataSecretRef, &out.KeyDataSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConnectionParameters.
func (in *ElasticsearchConnectionParameters) DeepCopy() *ElasticsearchConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FsInitParameters) DeepCopyInto(out *FsInitParameters) {
	*out = *in
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.MaxNumberOfSnapshots != nil {
		in, out := &in.MaxNumberOfSnapshots, &out.MaxNumberOfSnapshots
		*out = new(float64)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FsInitParameters.
func (in *FsInitParameters) DeepCopy() *FsInitParameters {
	if in == nil {
		return nil
	}
	out := new(FsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FsObservation) DeepCopyInto(out *FsObservation) {
	*out = *in
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.MaxNumberOfSnapshots != nil {
		in, out := &in.MaxNumberOfSnapshots, &out.MaxNumberOfSnapshots
		*out = new(float64)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FsObservation.
func (in *FsObservation) DeepCopy() *FsObservation {
	if in == nil {
		return nil
	}
	out := new(FsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FsParameters) DeepCopyInto(out *FsParameters) {
	*out = *in
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.Location != nil {
		in, out := &in.Location, &out.Location
		*out = new(string)
		**out = **in
	}
	if in.MaxNumberOfSnapshots != nil {
		in, out := &in.MaxNumberOfSnapshots, &out.MaxNumberOfSnapshots
		*out = new(float64)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FsParameters.
func (in *FsParameters) DeepCopy() *FsParameters {
	if in == nil {
		return nil
	}
	out := new(FsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcsInitParameters) DeepCopyInto(out *GcsInitParameters) {
	*out = *in
	if in.BasePath != nil {
		in, out := &in.BasePath, &out.BasePath
		*out = new(string)
		**out = **in
	}
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcsInitParameters.
func (in *GcsInitParameters) DeepCopy() *GcsInitParameters {
	if in == nil {
		return nil
	}
	out := new(GcsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcsObservation) DeepCopyInto(out *GcsObservation) {
	*out = *in
	if in.BasePath != nil {
		in, out := &in.BasePath, &out.BasePath
		*out = new(string)
		**out = **in
	}
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcsObservation.
func (in *GcsObservation) DeepCopy() *GcsObservation {
	if in == nil {
		return nil
	}
	out := new(GcsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GcsParameters) DeepCopyInto(out *GcsParameters) {
	*out = *in
	if in.BasePath != nil {
		in, out := &in.BasePath, &out.BasePath
		*out = new(string)
		**out = **in
	}
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GcsParameters.
func (in *GcsParameters) DeepCopy() *GcsParameters {
	if in == nil {
		return nil
	}
	out := new(GcsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HdfsInitParameters) DeepCopyInto(out *HdfsInitParameters) {
	*out = *in
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.LoadDefaults != nil {
		in, out := &in.LoadDefaults, &out.LoadDefaults
		*out = new(bool)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HdfsInitParameters.
func (in *HdfsInitParameters) DeepCopy() *HdfsInitParameters {
	if in == nil {
		return nil
	}
	out := new(HdfsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HdfsObservation) DeepCopyInto(out *HdfsObservation) {
	*out = *in
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.LoadDefaults != nil {
		in, out := &in.LoadDefaults, &out.LoadDefaults
		*out = new(bool)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HdfsObservation.
func (in *HdfsObservation) DeepCopy() *HdfsObservation {
	if in == nil {
		return nil
	}
	out := new(HdfsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HdfsParameters) DeepCopyInto(out *HdfsParameters) {
	*out = *in
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.LoadDefaults != nil {
		in, out := &in.LoadDefaults, &out.LoadDefaults
		*out = new(bool)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HdfsParameters.
func (in *HdfsParameters) DeepCopy() *HdfsParameters {
	if in == nil {
		return nil
	}
	out := new(HdfsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3InitParameters) DeepCopyInto(out *S3InitParameters) {
	*out = *in
	if in.BasePath != nil {
		in, out := &in.BasePath, &out.BasePath
		*out = new(string)
		**out = **in
	}
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.BufferSize != nil {
		in, out := &in.BufferSize, &out.BufferSize
		*out = new(string)
		**out = **in
	}
	if in.CannedACL != nil {
		in, out := &in.CannedACL, &out.CannedACL
		*out = new(string)
		**out = **in
	}
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.PathStyleAccess != nil {
		in, out := &in.PathStyleAccess, &out.PathStyleAccess
		*out = new(bool)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.ServerSideEncryption != nil {
		in, out := &in.ServerSideEncryption, &out.ServerSideEncryption
		*out = new(bool)
		**out = **in
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3InitParameters.
func (in *S3InitParameters) DeepCopy() *S3InitParameters {
	if in == nil {
		return nil
	}
	out := new(S3InitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Observation) DeepCopyInto(out *S3Observation) {
	*out = *in
	if in.BasePath != nil {
		in, out := &in.BasePath, &out.BasePath
		*out = new(string)
		**out = **in
	}
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.BufferSize != nil {
		in, out := &in.BufferSize, &out.BufferSize
		*out = new(string)
		**out = **in
	}
	if in.CannedACL != nil {
		in, out := &in.CannedACL, &out.CannedACL
		*out = new(string)
		**out = **in
	}
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.PathStyleAccess != nil {
		in, out := &in.PathStyleAccess, &out.PathStyleAccess
		*out = new(bool)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.ServerSideEncryption != nil {
		in, out := &in.ServerSideEncryption, &out.ServerSideEncryption
		*out = new(bool)
		**out = **in
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Observation.
func (in *S3Observation) DeepCopy() *S3Observation {
	if in == nil {
		return nil
	}
	out := new(S3Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Parameters) DeepCopyInto(out *S3Parameters) {
	*out = *in
	if in.BasePath != nil {
		in, out := &in.BasePath, &out.BasePath
		*out = new(string)
		**out = **in
	}
	if in.Bucket != nil {
		in, out := &in.Bucket, &out.Bucket
		*out = new(string)
		**out = **in
	}
	if in.BufferSize != nil {
		in, out := &in.BufferSize, &out.BufferSize
		*out = new(string)
		**out = **in
	}
	if in.CannedACL != nil {
		in, out := &in.CannedACL, &out.CannedACL
		*out = new(string)
		**out = **in
	}
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.PathStyleAccess != nil {
		in, out := &in.PathStyleAccess, &out.PathStyleAccess
		*out = new(bool)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.ServerSideEncryption != nil {
		in, out := &in.ServerSideEncryption, &out.ServerSideEncryption
		*out = new(bool)
		**out = **in
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Parameters.
func (in *S3Parameters) DeepCopy() *S3Parameters {
	if in == nil {
		return nil
	}
	out := new(S3Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotLifecycle) DeepCopyInto(out *SnapshotLifecycle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotLifecycle.
func (in *SnapshotLifecycle) DeepCopy() *SnapshotLifecycle {
	if in == nil {
		return nil
	}
	out := new(SnapshotLifecycle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotLifecycle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotLifecycleInitParameters) DeepCopyInto(out *SnapshotLifecycleInitParameters) {
	*out = *in
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]ElasticsearchConnectionInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpandWildcards != nil {
		in, out := &in.ExpandWildcards, &out.ExpandWildcards
		*out = new(string)
		**out = **in
	}
	if in.ExpireAfter != nil {
		in, out := &in.ExpireAfter, &out.ExpireAfter
		*out = new(string)
		**out = **in
	}
	if in.FeatureStates != nil {
		in, out := &in.FeatureStates, &out.FeatureStates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IgnoreUnavailable != nil {
		in, out := &in.IgnoreUnavailable, &out.IgnoreUnavailable
		*out = new(bool)
		**out = **in
	}
	if in.IncludeGlobalState != nil {
		in, out := &in.IncludeGlobalState, &out.IncludeGlobalState
		*out = new(bool)
		**out = **in
	}
	if in.Indices != nil {
		in, out := &in.Indices, &out.Indices
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxCount != nil {
		in, out := &in.MaxCount, &out.MaxCount
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.MinCount != nil {
		in, out := &in.MinCount, &out.MinCount
		*out = new(float64)
		**out = **in
	}
	if in.Partial != nil {
		in, out := &in.Partial, &out.Partial
		*out = new(bool)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.SnapshotName != nil {
		in, out := &in.SnapshotName, &out.SnapshotName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotLifecycleInitParameters.
func (in *SnapshotLifecycleInitParameters) DeepCopy() *SnapshotLifecycleInitParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotLifecycleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotLifecycleList) DeepCopyInto(out *SnapshotLifecycleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnapshotLifecycle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotLifecycleList.
func (in *SnapshotLifecycleList) DeepCopy() *SnapshotLifecycleList {
	if in == nil {
		return nil
	}
	out := new(SnapshotLifecycleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotLifecycleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotLifecycleObservation) DeepCopyInto(out *SnapshotLifecycleObservation) {
	*out = *in
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]ElasticsearchConnectionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpandWildcards != nil {
		in, out := &in.ExpandWildcards, &out.ExpandWildcards
		*out = new(string)
		**out = **in
	}
	if in.ExpireAfter != nil {
		in, out := &in.ExpireAfter, &out.ExpireAfter
		*out = new(string)
		**out = **in
	}
	if in.FeatureStates != nil {
		in, out := &in.FeatureStates, &out.FeatureStates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IgnoreUnavailable != nil {
		in, out := &in.IgnoreUnavailable, &out.IgnoreUnavailable
		*out = new(bool)
		**out = **in
	}
	if in.IncludeGlobalState != nil {
		in, out := &in.IncludeGlobalState, &out.IncludeGlobalState
		*out = new(bool)
		**out = **in
	}
	if in.Indices != nil {
		in, out := &in.Indices, &out.Indices
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxCount != nil {
		in, out := &in.MaxCount, &out.MaxCount
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.MinCount != nil {
		in, out := &in.MinCount, &out.MinCount
		*out = new(float64)
		**out = **in
	}
	if in.Partial != nil {
		in, out := &in.Partial, &out.Partial
		*out = new(bool)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.SnapshotName != nil {
		in, out := &in.SnapshotName, &out.SnapshotName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotLifecycleObservation.
func (in *SnapshotLifecycleObservation) DeepCopy() *SnapshotLifecycleObservation {
	if in == nil {
		return nil
	}
	out := new(SnapshotLifecycleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotLifecycleParameters) DeepCopyInto(out *SnapshotLifecycleParameters) {
	*out = *in
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]ElasticsearchConnectionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExpandWildcards != nil {
		in, out := &in.ExpandWildcards, &out.ExpandWildcards
		*out = new(string)
		**out = **in
	}
	if in.ExpireAfter != nil {
		in, out := &in.ExpireAfter, &out.ExpireAfter
		*out = new(string)
		**out = **in
	}
	if in.FeatureStates != nil {
		in, out := &in.FeatureStates, &out.FeatureStates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.IgnoreUnavailable != nil {
		in, out := &in.IgnoreUnavailable, &out.IgnoreUnavailable
		*out = new(bool)
		**out = **in
	}
	if in.IncludeGlobalState != nil {
		in, out := &in.IncludeGlobalState, &out.IncludeGlobalState
		*out = new(bool)
		**out = **in
	}
	if in.Indices != nil {
		in, out := &in.Indices, &out.Indices
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.MaxCount != nil {
		in, out := &in.MaxCount, &out.MaxCount
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.MinCount != nil {
		in, out := &in.MinCount, &out.MinCount
		*out = new(float64)
		**out = **in
	}
	if in.Partial != nil {
		in, out := &in.Partial, &out.Partial
		*out = new(bool)
		**out = **in
	}
	if in.Repository != nil {
		in, out := &in.Repository, &out.Repository
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
	if in.SnapshotName != nil {
		in, out := &in.SnapshotName, &out.SnapshotName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotLifecycleParameters.
func (in *SnapshotLifecycleParameters) DeepCopy() *SnapshotLifecycleParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotLifecycleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotLifecycleSpec) DeepCopyInto(out *SnapshotLifecycleSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotLifecycleSpec.
func (in *SnapshotLifecycleSpec) DeepCopy() *SnapshotLifecycleSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotLifecycleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotLifecycleStatus) DeepCopyInto(out *SnapshotLifecycleStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotLifecycleStatus.
func (in *SnapshotLifecycleStatus) DeepCopy() *SnapshotLifecycleStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotLifecycleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepository) DeepCopyInto(out *SnapshotRepository) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepository.
func (in *SnapshotRepository) DeepCopy() *SnapshotRepository {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotRepository) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepositoryElasticsearchConnectionInitParameters) DeepCopyInto(out *SnapshotRepositoryElasticsearchConnectionInitParameters) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EsClientAuthenticationSecretRef != nil {
		in, out := &in.EsClientAuthenticationSecretRef, &out.EsClientAuthenticationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyDataSecretRef != nil {
		in, out := &in.KeyDataSecretRef, &out.KeyDataSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepositoryElasticsearchConnectionInitParameters.
func (in *SnapshotRepositoryElasticsearchConnectionInitParameters) DeepCopy() *SnapshotRepositoryElasticsearchConnectionInitParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepositoryElasticsearchConnectionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepositoryElasticsearchConnectionObservation) DeepCopyInto(out *SnapshotRepositoryElasticsearchConnectionObservation) {
	*out = *in
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepositoryElasticsearchConnectionObservation.
func (in *SnapshotRepositoryElasticsearchConnectionObservation) DeepCopy() *SnapshotRepositoryElasticsearchConnectionObservation {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepositoryElasticsearchConnectionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepositoryElasticsearchConnectionParameters) DeepCopyInto(out *SnapshotRepositoryElasticsearchConnectionParameters) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.BearerTokenSecretRef != nil {
		in, out := &in.BearerTokenSecretRef, &out.BearerTokenSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.CAData != nil {
		in, out := &in.CAData, &out.CAData
		*out = new(string)
		**out = **in
	}
	if in.CAFile != nil {
		in, out := &in.CAFile, &out.CAFile
		*out = new(string)
		**out = **in
	}
	if in.CertData != nil {
		in, out := &in.CertData, &out.CertData
		*out = new(string)
		**out = **in
	}
	if in.CertFile != nil {
		in, out := &in.CertFile, &out.CertFile
		*out = new(string)
		**out = **in
	}
	if in.EndpointsSecretRef != nil {
		in, out := &in.EndpointsSecretRef, &out.EndpointsSecretRef
		*out = new([]v1.SecretKeySelector)
		if **in != nil {
			in, out := *in, *out
			*out = make([]v1.SecretKeySelector, len(*in))
			copy(*out, *in)
		}
	}
	if in.EsClientAuthenticationSecretRef != nil {
		in, out := &in.EsClientAuthenticationSecretRef, &out.EsClientAuthenticationSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.HeadersSecretRef != nil {
		in, out := &in.HeadersSecretRef, &out.HeadersSecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.KeyDataSecretRef != nil {
		in, out := &in.KeyDataSecretRef, &out.KeyDataSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.KeyFile != nil {
		in, out := &in.KeyFile, &out.KeyFile
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepositoryElasticsearchConnectionParameters.
func (in *SnapshotRepositoryElasticsearchConnectionParameters) DeepCopy() *SnapshotRepositoryElasticsearchConnectionParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepositoryElasticsearchConnectionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepositoryInitParameters) DeepCopyInto(out *SnapshotRepositoryInitParameters) {
	*out = *in
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = make([]AzureInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]SnapshotRepositoryElasticsearchConnectionInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Fs != nil {
		in, out := &in.Fs, &out.Fs
		*out = make([]FsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gcs != nil {
		in, out := &in.Gcs, &out.Gcs
		*out = make([]GcsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hdfs != nil {
		in, out := &in.Hdfs, &out.Hdfs
		*out = make([]HdfsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = make([]S3InitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = make([]URLInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Verify != nil {
		in, out := &in.Verify, &out.Verify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepositoryInitParameters.
func (in *SnapshotRepositoryInitParameters) DeepCopy() *SnapshotRepositoryInitParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepositoryInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepositoryList) DeepCopyInto(out *SnapshotRepositoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnapshotRepository, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepositoryList.
func (in *SnapshotRepositoryList) DeepCopy() *SnapshotRepositoryList {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepositoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotRepositoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepositoryObservation) DeepCopyInto(out *SnapshotRepositoryObservation) {
	*out = *in
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = make([]AzureObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]SnapshotRepositoryElasticsearchConnectionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Fs != nil {
		in, out := &in.Fs, &out.Fs
		*out = make([]FsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gcs != nil {
		in, out := &in.Gcs, &out.Gcs
		*out = make([]GcsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hdfs != nil {
		in, out := &in.Hdfs, &out.Hdfs
		*out = make([]HdfsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = make([]S3Observation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = make([]URLObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Verify != nil {
		in, out := &in.Verify, &out.Verify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepositoryObservation.
func (in *SnapshotRepositoryObservation) DeepCopy() *SnapshotRepositoryObservation {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepositoryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepositoryParameters) DeepCopyInto(out *SnapshotRepositoryParameters) {
	*out = *in
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = make([]AzureParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ElasticsearchConnection != nil {
		in, out := &in.ElasticsearchConnection, &out.ElasticsearchConnection
		*out = make([]SnapshotRepositoryElasticsearchConnectionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Fs != nil {
		in, out := &in.Fs, &out.Fs
		*out = make([]FsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gcs != nil {
		in, out := &in.Gcs, &out.Gcs
		*out = make([]GcsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Hdfs != nil {
		in, out := &in.Hdfs, &out.Hdfs
		*out = make([]HdfsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = make([]S3Parameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = make([]URLParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Verify != nil {
		in, out := &in.Verify, &out.Verify
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepositoryParameters.
func (in *SnapshotRepositoryParameters) DeepCopy() *SnapshotRepositoryParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepositoryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepositorySpec) DeepCopyInto(out *SnapshotRepositorySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepositorySpec.
func (in *SnapshotRepositorySpec) DeepCopy() *SnapshotRepositorySpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepositorySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotRepositoryStatus) DeepCopyInto(out *SnapshotRepositoryStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotRepositoryStatus.
func (in *SnapshotRepositoryStatus) DeepCopy() *SnapshotRepositoryStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotRepositoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLInitParameters) DeepCopyInto(out *URLInitParameters) {
	*out = *in
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.HTTPMaxRetries != nil {
		in, out := &in.HTTPMaxRetries, &out.HTTPMaxRetries
		*out = new(float64)
		**out = **in
	}
	if in.HTTPSocketTimeout != nil {
		in, out := &in.HTTPSocketTimeout, &out.HTTPSocketTimeout
		*out = new(string)
		**out = **in
	}
	if in.MaxNumberOfSnapshots != nil {
		in, out := &in.MaxNumberOfSnapshots, &out.MaxNumberOfSnapshots
		*out = new(float64)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLInitParameters.
func (in *URLInitParameters) DeepCopy() *URLInitParameters {
	if in == nil {
		return nil
	}
	out := new(URLInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLObservation) DeepCopyInto(out *URLObservation) {
	*out = *in
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.HTTPMaxRetries != nil {
		in, out := &in.HTTPMaxRetries, &out.HTTPMaxRetries
		*out = new(float64)
		**out = **in
	}
	if in.HTTPSocketTimeout != nil {
		in, out := &in.HTTPSocketTimeout, &out.HTTPSocketTimeout
		*out = new(string)
		**out = **in
	}
	if in.MaxNumberOfSnapshots != nil {
		in, out := &in.MaxNumberOfSnapshots, &out.MaxNumberOfSnapshots
		*out = new(float64)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLObservation.
func (in *URLObservation) DeepCopy() *URLObservation {
	if in == nil {
		return nil
	}
	out := new(URLObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *URLParameters) DeepCopyInto(out *URLParameters) {
	*out = *in
	if in.ChunkSize != nil {
		in, out := &in.ChunkSize, &out.ChunkSize
		*out = new(string)
		**out = **in
	}
	if in.Compress != nil {
		in, out := &in.Compress, &out.Compress
		*out = new(bool)
		**out = **in
	}
	if in.HTTPMaxRetries != nil {
		in, out := &in.HTTPMaxRetries, &out.HTTPMaxRetries
		*out = new(float64)
		**out = **in
	}
	if in.HTTPSocketTimeout != nil {
		in, out := &in.HTTPSocketTimeout, &out.HTTPSocketTimeout
		*out = new(string)
		**out = **in
	}
	if in.MaxNumberOfSnapshots != nil {
		in, out := &in.MaxNumberOfSnapshots, &out.MaxNumberOfSnapshots
		*out = new(float64)
		**out = **in
	}
	if in.MaxRestoreBytesPerSec != nil {
		in, out := &in.MaxRestoreBytesPerSec, &out.MaxRestoreBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.MaxSnapshotBytesPerSec != nil {
		in, out := &in.MaxSnapshotBytesPerSec, &out.MaxSnapshotBytesPerSec
		*out = new(string)
		**out = **in
	}
	if in.Readonly != nil {
		in, out := &in.Readonly, &out.Readonly
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new URLParameters.
func (in *URLParameters) DeepCopy() *URLParameters {
	if in == nil {
		return nil
	}
	out := new(URLParameters)
	in.DeepCopyInto(out)
	return out
}
